# -*- coding: utf-8 -*-
"""exception_handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lxlK30AiPD5lS-QiUFaIG7dQWqIrZ0B9
"""

import math

help(math)

math.sqrt(25)

import random

random.randint(0,100)

print(random.randint(0,100))
print(random.randint(0,100))
print(random.randint(0,100))
print(random.randint(0,100))

random.seed(3)
print(random.randint(0,100))
print(random.randint(0,100))
print(random.randint(0,100))
print(random.randint(0,100))

random.seed(3)
print(random.randint(0,100))
print(random.randint(0,100))
print(random.randint(0,100))
print(random.randint(0,100))

from math import *

sqrt(25)

floor(25.4)

import langchain

import bs4

"""#Exception Handling"""

1/0

print(a_not_defined)

if 573
  print("hello")

if 573:
print("hello")

print("bye") # so anything after an exception has occurred, will not be executed.

import module_random_which_does_not_exist

"random i am".sort()

# try and except blocks

def divide(a,b):
  return a/b

divide(10,0)
print("bye")

def divide(a,b):
  return a/b

try:
  print(divide(10,0))
except:
  print("You are not supposed to divide by 0. Try again")

def i_divide_by_zero(a):
    return a / 0

try:
    # i_divide_by_zero(5)
    print(5 + 4)
    # any amount of code
except:
    print("Why are you dividing by zero?")

# Getting what exception is occuring -

l1 = [2, 0, "hello", None]

for e in l1:
    try:
        print(f"Current element - {e}")
        result = 5 / int(e)
        print(f"Result - {result}")
    except Exception as exp:
        print(f"Excpetion - {exp}")

    print("-"*50)

print("Execution Successful!")

try:
    print("I am trying!")
    #1/0
except:
    print("Exception")
finally:
    print("FINALLY")

try:
    print("I am trying!")
    print(1/2)
except:
    print("Except")

print("FINALLYYY!")

"""HOMEWORK
-Find out why finally exists when we can achieve same code structure using a print statement.
"""

raise Exception("This password is incorrect!")

Exception("This password is incorrect!")

raise ZeroDivisionError

num = 5
if num%2 != 0:
    raise Exception("Number is odd!")

class MyCustomException(Exception):
    def __init__(self, message):
        super().__init__(message)

name = "Sach"
try:
    if len(name)<5:
        raise MyCustomException("Length of name must be >4 characters")
    else:
        print("Name:", name)

except MyCustomException as e:
    print(e)

"""# Quiz"""

try:
    assert False, "Error occurred!"
except AssertionError as e:
    print(e)

assert False, "Error occurred!"

l1 = [2, 0, "hello", None]

for e in l1:
    try:
        result = 5 / int(e)
        print("N")
    except Exception as ex:
        print("E")
    except ZeroDivisionError as z:
        print("Z")

l1 = [2, 0, "hello", None] # order of exception handling matters

for e in l1:
    try:
        result = 5 / int(e)
        print("N")
    except ZeroDivisionError as z:
        print("Z")
    except Exception as ex:
        print("E")

l1 = [2, 0, "hello", None] # order of exception handling matters

for e in l1:
    try:
        result = 5 / int(e)
        print("N")
    except ZeroDivisionError as z:
        print("Z")

assert "Hello" == "Bye", "values not the same"

