# -*- coding: utf-8 -*-
"""ps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13gvZl4Tpf7C7DV1_ydCVjtLU7C5XGwYF
"""

# Question 1: What will be the output of the following code snippet?


x = 10
y = "20"
print(type(y))
z = int(y) + x
print(type(z), z)

# q2 What will be the output of the following Python code?


x = 5
y = 2
z = x ** y // y + x % y - y * 2
print(z)

A) 9
B) 11
C) 6
D) 5

(a^b%c)+((a//b)∗(b+c))−(a and b or c)

def evaluate_expression(a,b,c) :
  res = (a**b%c)+((a//b) * (b+c)) - (a and b or c)
  return res

print(evaluate_expression(5, 3, 2))

You are developing a banking system that determines a user’s
transaction approval based on the following rules:

If the user is verified (verified == True):`
If the account balance is greater than or equal to the withdrawal amount, approve the transaction.
Otherwise, deny the transaction due to insufficient balance.
If the user is not verified, deny the transaction.
Write a Python function process_transaction(verified, balance, withdraw_amount) that returns:
"Transaction Approved" if conditions are met.
"Transaction Denied: Insufficient Balance" if the balance is low.
"Transaction Denied: User Not Verified" if the user is not verified.

def process_transaction(verified, balance, withdraw_amount):
  if verified:  # Check if the user is verified
     if balance >= withdraw_amount:  # Check if balance is enough
        return "Transaction Approved"
     else:
        return "Transaction Denied: Insufficient Balance"
  else:
     return "Transaction Denied: User Not Verified"

print(process_transaction(True, 1000, 500))   # Expected Output: Transaction Approved
print(process_transaction(True, 300, 500))    # Expected Output: Transaction Denied: Insufficient Balance
print(process_transaction(False, 1000, 500))  # Expected Output: Transaction Denied: User Not Verified

# What will be the output of the following Python code?


temperatures = [25, 30, 28, 32, 27]

for temp in range(len(temperatures)):
    print(temperatures[temp], end=" | ")

Options:

A) 25 | 30 | 28 | 32 | 27 |
B) 25 30 28 32 27
C) 25 | 30 | 28 | 32 | 27
D) Syntax Error

def add(a,b) :
  print(a+b)

add(10,20) + 30

def add2(a,b) :
  return a + b


type(add2(10,20))

a = 10
b = 20
c = 30

c
b

a = 10
b = 20
c = 30

print(c)
print(b)

# What will be the output of the following Python code?


temperatures = [25, 30, 28, 32, 27]

for temp in range(len(temperatures)):
    print(temperatures[temp],end=" | ")

# Options:

# A) 25 | 30 | 28 | 32 | 27 |
# B) 25 30 28 32 27
# C) 25 | 30 | 28 | 32 | 27
# D) Syntax Error

print("mlv",end=" | ")
print("prasad",end=" | ")
print("mentor",end= " | ")
print("scaler",end= " | ")

stock = 5
while stock:
    print(stock, end=", ")
    stock -= 2
    if stock <= 0:
        break

A) 5, 3, 1,
B) 5, 3, 1, -1,
C) 5 3 1
D) Infinite loop

You are developing an online order tracking system.
Customers place N orders, and your system processes them
in batches of 3 orders at a time. If an order count is not a
multiple of 3, it processes the remaining orders separately.
Write a function process_orders(n_orders) that prints batch-wise processing.

Example Input & Output:
process_orders(8)

Output:
Processing orders: [1, 2, 3]
Processing orders: [4, 5, 6]
Processing orders: [7, 8]

for i in range(1, 4):
  for j in range(1, 4):
      if i == j:
          continue
      print(f"({i}, {j})", end=" ")

Options:

A) (1, 2) (1, 3) (2, 1) (2, 3) (3, 1) (3, 2)
B) (1, 1) (1, 2) (1, 3) (2, 1) (2, 2) (2, 3) (3, 1) (3, 2) (3, 3)
C) (1, 2) (1, 3) (2, 1) (2, 3) (3, 1) (3, 3)
D) (1, 2) (2, 3) (3, 1)

Question 9: You are creating a custom multiplication
table generator for students.

The table should:

Print numbers in a 5x5 format (1 to 5).
Highlight multiples of 3 by surrounding them with [*].
Skip printing multiples of 4 using continue.
Example Output for n=5:
1 2 [*3*] 5 [*6*]
7 [*9*] 10 11 13
14 [*15*] 17 [*18*] 19
[*21*] 22 23 25

n = 6
ct = 0
for i in range(1,n**2+1):
  if i %4 == 0 :
    continue
  elif i %3 == 0 :
    print("[*"+str(i)+"*]",end=" ")
    ct = ct + 1
  else :
    print(i,end=" ")
    ct = ct + 1

  if ct %5 == 0 :
    # print("----------")
    print()

print("mlv",end=" ")
print("prasad",end=" ")

print("nandi",end=" ")
# print()
print("rohit",end=" ")
print("kohli",end=" ")

Example Input & Output:
print(gcd_lcm(8, 12))

Output:
GCD: 4, LCM: 24

add = lambda x, y=5: x + y
print(add(2))
print(add(2, 3))

nums = [3, 1, 4, 1, 5]
nums.append(9)
print(nums)
nums.sort()
print(nums)
for i in range(4, -1, -2):
    # print(i)/
    print(nums[i], end=" ")

for i in range(-1,-9,-2) :
  print(i,end=" ")

