# -*- coding: utf-8 -*-
"""oops2_18Nov.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EZOzWheynxUSanoC08rXU0L2ugZaWktj
"""

class Car:
  def __init__(self, name, mileage):
    self.name = name
    self.mileage = mileage

c1 = Car("Nexon", 12)
c2 = Car("Altroz", 15)

print(c1)

x = 2
print(type(x))

print(type(c1)) # __main__ means the object belongs to a class in the current code

class Car:
  def __init__(self, name, mileage):
    self.name = name
    self.mileage = mileage

  def __str__(self):
    return f"{self.name} -> {self.mileage}"

  def __add__(self, other): # other is an object of class car
    return self.mileage + other.mileage

  def __lt__(self, other):
    return self.mileage < other.mileage

  def __eq__(self, other):
    return self.mileage == other.mileage

c1 = Car("Nexon", 12)
c2 = Car("Altroz", 12)

print(c1)

c1 + c2

c1 < c2
# __lt__(c1,c2)

c1 > c2

c1 == c2

2 == 2

# Quiz
class A:
  def __init__(self, a):
    self.a = a
  def __add__(this, b):
    if isinstance(b, int):
      return A(this.a + b)
    return A(this.a + b.a)
  def __str__(self):
    return f"{self.a}"


one = A(1)
two = A(2)
three = A(3)

print(one + two + 100)
print(one + two + three)

print(one + two + 100.0)

class Parent:
  def __init__(self):
    #self.a = a
    print("parent class")

class Child(Parent):
  def __init__(self):
    #self.a = a
    print("child class")

p = Parent()

c = Child()

class SchoolMember:
  def __init__(self,name):
    self.name = name

class Student(SchoolMember):
  def __init__(self, name, grade):
    self.grade = grade

class Staff(SchoolMember):
  def __init__(self, name, salary):
    self.salary = salary

class Teacher(Staff):
  def __init__(self, name, salary, subject):
    self.subject = subject

s1 = Student("Krishna","A")

print(type(s1))

s1.grade

s1.name # access to parent class property denied

from typing import NamedTuple
class SchoolMember:
  def __init__(self,name):
    self.name = name

class Student(SchoolMember):
  def __init__(self, name, grade):
    super().__init__(name)
    self.grade = grade

class Staff(SchoolMember):
  def __init__(self, name, salary):
    super().__init__(name)
    self.salary = salary

class Teacher(Staff):
  def __init__(self, name, salary, subject):
    super().__init__(name,salary)
    self.subject = subject

s1 = Student("Krishna","A")

print(type(s1))

s1.name

t1 = Teacher("Pulkit",1000,"Python")

print(t1.name, t1.salary, t1.subject)

class A:
    def do_something(self):
        print("I do something!", end=" ")

class B(A):
    def do_something(self):
        super().do_something()
        print("I also do something!", end=" ")

b = B()
c.do_something()

class BankAccount:
  def __init__(self, balance):
      self.balance = balance

  def withdrawl(self, amount):
      self.balance -= amount

  def deposit(self, amount):
      self.balance += amount

b1 = BankAccount(10000)

b1.deposit(5000)

b1.balance

b1.withdrawl(15000)

b1.balance

b1.balance = 12345567890

print(b1.balance)

class BankAccount:
  def __init__(self, balance):
      self.__balance = balance # private property

  # setters
  def withdrawl(self, amount):
      self.__balance -= amount

  def deposit(self, amount):
      self.__balance += amount

  # getter
  def check_balance(self):
    return self.__balance

b2 = BankAccount(1000)

b2.__balance

b2.deposit(1000)
b2.withdrawl(500)

b2.check_balance()

b2.__balance = 0

b2.check_balance()

dir(b2)

b2._BankAccount__balance = 0

b2.check_balance()

b2.__dict__

b2.quantity = 10
b2.__dict__

b2.__balance = 10

b2.__dict__

"""### Least frequent from back"""

aaaadfhgajshfdmmmssssmmm

ajjaajja

#s = "aaaadfhgajshfdmmmssssmmm"
s = "ajjaajja"
d = {}
for i in s:
  if i in d:
    d[i] += 1
  else:
    d[i] = 1

print(d)

m = min(d.values())
sub = {}
for i,j in d.items():
  if j == m:
    sub[i] = j

def check(sub):
  if len(sub) == 1:
    return list(sub.keys())[0]

  for i in range(len(s)-1,-1,-1):
    if s[i] in sub:
      return s[i]

check(sub)

list(d.keys())[0]

"""## scaler solution"""

def count_char(string):
  hash = {}
  for ch in string[::-1]:
    if hash.get(ch, None) != None:
      hash[ch] += 1
    else:
      hash[ch] = 1

  least_freq = (None, float("inf"))

  for ch, freq in hash.items():
    if hash[ch] < least_freq[1]:
      least_freq = (ch, hash[ch])

  return least_freq[0]