# -*- coding: utf-8 -*-
"""regex_2Dec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDWXclj6E7WGvYNnnoLeUP8iV_Xs4sFc
"""

import re # importing regex library

def is_vemail(s):
  email_pattern = "^\w+([\.-]?\w+)*@\w+([|.-]?\w+)*(\.\w{2,3})+$"
  res = re.search(email_pattern, s)
  # scans through string looking for the first location where pattern is found
  if res:
    return True
  else:
    return False

is_vemail("abcd@gmail")

is_vemail("abcd@xy.sx")

is_vemail("nikhil.sanghi@scaler-academy.co.in")

!gdown 1sSDV5UspYZL3UUOGuiuxppSGcv1wS9ex

data = open("data.txt", "r").read()
print(data[:500]) # display some data

type(data)

pattern = "\d{3}-\d{3}-\d{4}"
print(re.match(pattern,data))

print(re.search(pattern,data))

data[12:24]

phone_numbers = re.findall(pattern,data)
len(phone_numbers)

print(re.finditer(pattern,data))

"""general structure - (string1)@(string2).(2+characters)"""

email_pattern = "\w+@\w+\.[a-z]{2,3}"

emails = re.findall(email_pattern, data)
len(emails)

name_pattern = "[A-Z][a-z]+\s[A-Z][a-z]+"

re.search(name_pattern, "Pulkit Aneja")

"""Quiz"""

re.match('ab?','abb')

x='[0-9]+'
re.findall(x, '7 apples and 4 mangoes')

!wcurl