# -*- coding: utf-8 -*-
"""oops_15Nov.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0s_ay3qjpdhe3wgn6Yi3ZX1z3VrjKfo
"""

s1 = {2,3,4,5}
s2 = {1,3,4,6,7,8}

s1.symmetric_difference(s2)

s2.symmetric_difference(s1)

s1 ^ s2

"""# OOPS"""

# user defined class
class Student:
  # methods
  # properties
  pass

# create an instance of student
s1 = Student() # s1 is an object

type(s1)

s = set()
print(type(s))

isinstance(s1, Student)

isinstance(s, Student)

isinstance(s, set)

"""# Polymorphism # methods and operators"""

# + operator
print(56 + 35)

print("Pulkit" + "Aneja")

list: pop()
set pop()

class Student:
  def hello(self): # placeholder for the object of the class
    print("hello all")

s1 = Student()

s1.hello()

a = [1,2,3,4]
a.append(5) # append(a,5)

class Student:
  def __init__(self, naam, umar):
    self.name = naam
    self.age = umar


s1 = Student("Raghav",28)

print(s1.name)
print(s1.age)

s2 = Student()

s2 = Student("Rohit",26)

print(s2.name, s2.age)

class Dog:
  kind = "canine" # class variable

  def __init__(self, name):
    self.name = name

d1 = Dog("Tommy")
d2 = Dog("Tuffy")

print(d1.name, d2.name)

print(d1.kind, d2.kind)

d1.name = "Scooby"

d1.name

d1.kind = "Bull Dog" # d1 now has an instance variable kind and its value is bull dog

d2.kind

d1.kind

d2.name = "Charlie"

d2.name

class Student:
    name = "Bipin" # class variable
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def hello(self):
      print(f"Hello {self.name}")

s3 = Student("Ayush", 20)
s3.hello() # if instance and class variables have the same name, the instance variable will be called out by the object

"""# after class doubts"""

d2.age = 3

d2.age

d1.age

