# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFiyTV_iBdDqUI9_lq-m0EgpPg7EWrf9

**Q2. compute GPA**

**Problem Description:**

Create a class Student and initialize it with the following class variables:

* marks in subject 1
* credit of subject 1
* marks in subject 2
* credit of subject 2

Create a function ***gradepointaverage()*** for the Student class which computes the GPA rounded to two decimals, based on the following criteria of points in a subject :

1. If marks>=90:10 points
2. If 90>marks>=75: 9 points
3. If 75>marks>=60: 8 points
4. If 60>marks>=45: 7 points
5. If marks<45: 0 points

GPA = (pointsinsubject1∗creditofsubject + pointsinsubject2∗creditofsubject2) / (creditofsubject1 + creditofsubject2)

The points in a subject should be calculated according to the criteria mentioned in the question.

Also, implement a special zero case to handle when credits of both subjects are 0, return "-1.0".
"""

def subject_points(marks):
    points = 0
    if marks >= 90:
        points = 10
    elif marks >= 75:
        points = 9
    elif marks >= 60:
        points = 8
    elif marks >= 45:
        points = 7
    return points

class Student():

    def __init__(self, marks1,marks2,credits1, credits2):
        #YOUR CODE GOES HERE
        self.marks1 = marks1
        self.marks2 = marks2
        self.credits1 = credits1
        self.credits2 = credits2

    def __str__(self) -> str:
       return f"Student(marks1={self.marks1}, marks2={self.marks2}, credits1={self.credits1}, credits2={self.credits2})"

    def grade_point_average(self):
        gpa=0

        #YOUR CODE GOES HERE
        credits_sum = self.credits1 + self.credits2
        if credits_sum > 0:
            gpa = (subject_points(self.marks1) * self.credits1
                        + subject_points(self.marks2) * self.credits2) / credits_sum
        else:
            gpa = -1.0
        gpa = round(gpa, 2)
        return gpa

student1 = Student(85, 76, 3, 4)
print(f"{student1}.gpa = {student1.grade_point_average()}")

"""**Q3. Total electricity bill**

Create a class **Bill** and initialize it with the details: **previous** and **current** meter readings. Create a function **total_bill()** inside the Bill class which returns the total bill based on the following criteria:

1. For the first 100 units consumed: 3.5 rs/unit
2. For the next 100 units consumed: 5 rs/unit
3. For remaining units consumed: 8 rs/unit
4. Meter Charges: 150 rs (It's included only once but is mandatory)
"""

def window_bill(units, window_max, rate_per_unit):
    window_bill_units = units if units < window_max else window_max
    bill_amt = window_bill_units * rate_per_unit
    return (bill_amt, (units - window_bill_units))

class Bill():

    def __init__(self, prev_read, cur_read):
        #YOUR CODE GOESS HERE
        self.prev_read = prev_read
        self.cur_read = cur_read

    def __str__(self) -> str:
        return f"Bill(prev_read={self.prev_read}, cur_read={self.cur_read})"

    def total_bill(self):
        total=0.0
        #YOUR CODE GOESS HERE
        units = self.cur_read - self.prev_read
        first_window_bill, units = window_bill(units, 100, 3.5)
        second_window_bill, units = window_bill(units, 100, 5.0)
        third_window_bill = units * 8.0
        total = first_window_bill + second_window_bill + third_window_bill + 150.0
        total = round(total, 2)

        return total

bill1 = Bill(200, 650)
print(f"{bill1}.total_bill() = {bill1.total_bill()}")

"""**Q6. Print name**

What will be the output of the following code snippet:

```python
class People():
    def __init__(self, name):
        self.name = name

    def get_name(self):
        print(self.name)

person1 = People("John")
person2 = People("Mary")
person1.get_name()
```
"""

class People():
    def __init__(self, name):
        self.name = name

    def get_name(self):
        print(self.name)

person1 = People("John")
person2 = People("Mary")
person1.get_name()

"""**AQ1. fruits quantity in bag**

What will be the output of the following Python code?

```python
class fruits:
    def __init__(self, price):
        self.price = price

obj=fruits(50)
obj.quantity=10
obj.bags=2

print(obj.quantity+len(obj.__dict__))
```
"""

class fruits:
    def __init__(self, price):
        self.price = price

obj=fruits(50)
obj.quantity=10
obj.bags=2

print(obj.quantity+len(obj.__dict__))

"""**AQ2. football**

What is the output of the following code snippet?

```python
class football:
    final_res= 'lose'
    def __init__(self,name,score):
        self.name = name
        self.score = score
        self.final_res = 'lose'
    
    def calc(self, winning_score):
        if self.score>winning_score:
            self.final_res='win'
match = football('Juventus',3)
match.calc(2)
print(football.final_res, match.final_res)
```
"""

class football:
    final_res= 'lose'
    def __init__(self,name,score):
        self.name = name
        self.score = score
        self.final_res = 'lose'

    def calc(self, winning_score):
        if self.score>winning_score:
            self.final_res='win'
match = football('Juventus',3)
match.calc(2)
print(football.final_res, match.final_res)

"""**AQ3. student marks**

Given the following block of code, what will be the expected output?

```python
class Student:
    def __init__(self,roll,marks):
        self.roll = roll
        self.marks = marks
    def display(self):
        print('Roll:', self.roll,'Marks:',self.marks, end=" ")

student1 = Student(34,'A')
student1.age = 17
print(student1.display(), 'Age:',student1.age)
```
"""

class Student:
    def __init__(self,roll,marks):
        self.roll = roll
        self.marks = marks
    def display(self):
        print('Roll:', self.roll,'Marks:',self.marks, end=" ")

student1 = Student(34,'A')
student1.age = 17
print(student1.display(), 'Age:',student1.age)

"""**AQ4. class and constructor**

Fill the blanks in the code snippet to get **Emma 10 Machine Learning** as the output.

```python
class Student:
  # Class variable
  subject_name = 'Math for Machine Learning'

  # constructor
  def __init__(self, name, roll_no):
    self.name = name
    self.roll_no = roll_no

# outside the class
# create Objects
???

print(s1.name, s1.roll_no, s1.subject_name)
```
"""

class Student:
  # Class variable
  subject_name = 'Math for Machine Learning'

  # constructor
  def __init__(self, name, roll_no):
    self.name = name
    self.roll_no = roll_no

# outside the class
# create Objects
s1 = Student('Emma', 10)
s1.subject_name = 'Machine Learning'
print(s1.name, s1.roll_no, s1.subject_name)
s2 = Student('Anna', 10)
print(s2.name, s2.roll_no, s2.subject_name)

s1 = Student('Emma', 10)
Student.subject_name = 'Machine Learning'
print(s1.name, s1.roll_no, s1.subject_name)

"""**AQ5. class solution**

What will be the output of the following code snippet?

```python
class solution:
  def initial(self,sets):
    return self.final(sets)

  def final(self, sets):
    return list(map(lambda x: ((x**3)%2==0,x**3),sets))

print(solution().initial([4,5,6]))
```
"""

class solution:
  def initial(self,sets):
    return self.final(sets)

  def final(self, sets):
    return list(map(lambda x: ((x**3)%2==0,x**3),sets))

print(solution().initial([4,5,6]))

"""**AQ6. Stocks of a product**

You are tasked with creating a basic structure for managing products in an online store using Python. Implement a class called Product with the following specifications:

1. The Product class should be initialized with the following attributes: ***product_id***, ***name***, ***price***, and ***quantity***. These attributes should be publicly accessible.

2. Implement a method **display_info** within the Product class. This method should print the details of the product, including its product_id, name, price, and quantity as follows.
```
Product ID:
Name:
Price: $
Quantity:
```
3. Add two methods to the Product class for stock management:

    * **add_stock(count):** This method should increase the quantity of the product by the given count.
    * **sell_stock(count):** This method should decrease the quantity of the product by the given count, If count to sell are more than current quantity it should print "Not enough stock to sell"

Your implementation should allow for creating instances of the Product class with specific values for each attribute and should enable basic stock management through the add_stock and sell_stock methods.
"""

class Product:
    def __init__(self, product_id, name, price, quantity):
        # complete the method
        self.product_id = product_id
        self.name = name
        self.price = price
        self.quantity = quantity

    def display_info(self):
        # complete the method
        print(f"Product ID: {self.product_id}\nName: {self.name}\nPrice: ${self.price}\nQuantity: {self.quantity}")

    # Method to add stock
    def add_stock(self, count):
        # complete the method
        self.quantity += count

    # Method to sell stock
    def sell_stock(self, count):
        # complete the method
        if self.quantity < count:
            print('Not enough stock to sell')
        else:
            self.quantity -= count

p1 = Product('P123', 'Smartphone', '299.99', 50)
p1.display_info()
p1.add_stock(20)
p1.display_info()
p1.sell_stock(100)
p1.display_info()