# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9YR2xL3cGauDssWmcJ1XNPiJG0MplfT

$\newcommand{\trinom}[3]{\begin{pmatrix} #1 \\ #2 \\ #3 \end{pmatrix}}$

# **Q1. percentile-and-quantile-coding**

**Problem Description**

Build an interactive calculator that computes the **quantile** or **percentile** of the input list according to the formula and the n, i.e (list, formula, n). Calculator should follow the following rules:

1. If the length of the input list is 0, raise Exception with the message "**Null value passed**"
2. If the formula is either "Quantile" or "Percentile", return the nth percentile/quantile of the list.
3. If the formula entered is other than "Quantile" or "Percentile", raise Exception with message "**Formula Error: Wrong Formula**"
"""

import numpy as np
def calc(a: list,b: str, c):
  """
  a is list, b is string, c is integer
  return the exception in msg
  """
  b = b.lower()
  if a == None or len(a) == 0:
    raise ValueError("Null value passed")
  if b == "quantile":
    return np.quantile(a,c)
  elif b == "percentile":
    return np.percentile(a,c)
  else:
    raise ValueError("Formula Error: Wrong Formula")

l = [1,2,3,4,5]
formula = "Percentile"
c = 25
print(f"calc({l}, {formula}, {c}) = {calc(l, formula, c)}")

"""# **Q2. Except and finally**

Is the following way of using try, except, and finally valid? What's the reason behind your answer?

```python
try:
  print(a)
except ValueError:
  a=3
  print(a)
except:
  a=5
  print(a)
finally:
  a=4
  print(a)
````

#### **Ans:**

Yes, valid, because all that matters is except should be used above finally
"""

try:
  print(a)
except ValueError:
  a=3
  print(a)
except:
  a=5
  print(a)
finally:
  a=4
  print(a)

"""# **Q3. type of error**

Suppose func(file_name) is a function that takes a .txt file as an argument and prints the text in the file.

Now, if the file goes missing from the referred location, then what kind of exception will be raised?

#### **Ans:**

FileNotFoundError

# **Q4. Which except statement?**

Which of the except statement out of #1 and #2 will get executed in the following code snippet?

```python
try:
  print(x)
except NameError:                       #1
  print("Variable x is not defined")
except:                                 #2
  print("Something else went wrong")
````

#### **Ans:**

NameError prints "Variable x is not defined"
"""

try:
  print(x)
except NameError:                       #1
  print("Variable x is not defined")
except:                                 #2
  print("Something else went wrong")

"""# **Q5. finally block**

What will statements #A and #B print?

```python
def even(x):
  try:
    if x%2==0:
      return "even"
    else:
      raise Exception
  except:
    return("odd")
  finally:
    return "integer"

print(even(5))    #A
print(even(4))    #B
```
"""

def even(x):
  try:
    if x%2==0:
      return "even"
    else:
      raise Exception
  except:
    print("Inside except")
    return("odd")
  finally:
    print("Inside finally")
    return "integer"

print(even(5))    #A
print(even(4))    #B

"""# **AQ1. What will the code do?**

What will the following code snippet do:

```python
import random

array = list(range(100))
random.shuffle(array)
while len(array) != 0:
      print(array.pop())
```
"""

import random

array = list(range(100))
random.shuffle(array)
while len(array) != 0:
      print(array.pop())

"""# **AQ2. Euler's number**

Complete the following code snippet to compute the value of Euler’s number e:

e = 1 + 1/1! + 1/2! + ... + 1/n!

```python
import math
result = 1
for i in range(1,7):
     result += _______________#blank1
print(round(result,2))
```
"""

import math

def euler(n):
  result = 1
  for i in range(1,n+1):
    result += 1/math.factorial(i)
  return round(result,2)

n = 7
print(f"euler({n}) = {euler(n)}")

"""# **AQ3. Mean and standard deviation**

Which of the options can be used to calculate the mean and standard deviation of the list a in the code snippet given below?

```python
import math
import numpy as np
a=[1,2,3,45]
```
"""

import math
import numpy as np
a=[1,2,3,45]
print(f"Mean: {np.mean(a)}")
print(f"Standard Deviation: {np.std(a)}")

"""# **AQ4. Raising exception**

What will be the output of code below?

```python
def input_name(name):
  try:
    # name = input("Enter your name: ")
    if len(name) < 5:
      raise Exception("Name cannot have less than 5 characters")
    elif len(name)==5:
      raise Exception("Name should have more than 5 characters")

  except Exception as e:
    print("Error occured :",e)

input_name("mangoes")
input_name("apple")
input_name("fig")
```
"""

def input_name(name):
  try:
    # name = input("Enter your name: ")
    if len(name) < 5:
      raise Exception("Name cannot have less than 5 characters")
    elif len(name)==5:
      raise Exception("Name should have more than 5 characters")

  except Exception as e:
    print("Error occured :",e)

print(input_name("mangoes"))
print(input_name("apple"))
print(input_name("fig"))

"""# **AQ5. exception in python**

What is the output of this code?

```python
class MyError(Exception):

    # Constructor or Initializer
    def __init__(self, value):
        self.value = value

    # __str__ is to print() the value
    def __str__(self):
        return(repr(self.value))


try:
    raise(MyError(3*2))

# Value of Exception is stored in error
except MyError as error:
    print('A New Exception occurred: ', error.value)
```
"""

class MyError(Exception):

    # Constructor or Initializer
    def __init__(self, value):
        self.value = value

    # __str__ is to print() the value
    def __str__(self):
        return(repr(self.value))


try:
    raise(MyError(3*2))

# Value of Exception is stored in error
except MyError as error:
    print('A New Exception occurred: ', error.value)

"""# **AQ6. Geometric Shape Area Calculator with Specific Errors**

**Background:** Develop a Python function for calculating the area of various geometric shapes, including circles, rectangles, and triangles.

**Task:** Implement a function named calculate_area that takes two parameters: a string representing the shape and a tuple of dimensions. The function should calculate the area for circles, rectangles, and triangles based on these dimensions.

**Input Specifications:**

* The function accepts two arguments: the shape name (a string, one of `"circle"`, `"rectangle"`, or `"triangle"`) and dimensions (a tuple).
* Circle: Requires one dimension (radius).
* Rectangle: Requires two dimensions (length, width).
* Triangle: Requires two dimensions (base, height).

**Expected Output:**

* The function should return the area of the shape as a float rounded by 2 decimal places
* If an unknown shape is provided, It should raise the `ValueError` with message `f"Unknown shape: {shape}"`.
* If the dimensions are incorrect for the shape (e.g., negative numbers, incorrect number of dimensions), It should raise `ValueError` with message `f"Invalid dimensions for shape: {shape}"`.

**Input Sample 1**
"rectangle"
(10, 5)

**Output Sample 1:**
50

**Input Sample 2**
"hexagon"
(10, 5)

**Output Sample 2:**
Unknown shape: hexagon

**Input Sample 3**
"circle"
(-10, )

**Output Sample 3:**
Invalid dimensions for shape: circle
"""

import math

def calculate_area(shape, dimensions):
  # complete the function
  area = 0
  shape = shape.lower()
  if shape == "circle":
    if len(dimensions) != 1 or dimensions[0] < 0:
      raise ValueError(f"Invalid dimensions for shape: {shape}")
    r = dimensions[0]
    area = math.pi * r * r
  elif shape == "rectangle":
    if len(dimensions) != 2 or dimensions[0] < 0 or dimensions[1] < 0:
      raise ValueError(f"Invalid dimensions for shape: {shape}")
    area = dimensions[0] * dimensions[1]
  elif shape == "triangle":
    if len(dimensions) != 2 or dimensions[0] < 0 or dimensions[1] < 0:
      raise ValueError(f"Invalid dimensions for shape: {shape}")
    area = 0.5 * dimensions[0] * dimensions[1]
  else:
    raise ValueError(f"Unknown shape: {shape}")
  return round(area, 2)

shape = "rectangle"
dimensions = (10, 5)
print(f"calculate_area({shape}, {dimensions}) = {calculate_area(shape, dimensions)}")

# shape = "hexagon"
# dimensions = (10, 5)
# print(f"calculate_area({shape}, {dimensions}) = {calculate_area(shape, dimensions)}")

shape = "circle"
dimensions = (-10, )
print(f"calculate_area({shape}, {dimensions}) = {calculate_area(shape, dimensions)}")