# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFiyTV_iBdDqUI9_lq-m0EgpPg7EWrf9

$\newcommand{\trinom}[3]{\begin{pmatrix} #1 \\ #2 \\ #3 \end{pmatrix}}$

# **Q1. Values**

Let a = [4, 1, 3] and b = [7, 1, 9] be two vectors. What are the values of 4a - 3b and -7a + b respectively?

#### **Ans:**

4a - 3b = 4 $\trinom{4}{1}{3}$ - 3 $\trinom{7}{1}{9}$ = [-5, 1, -15]

-7a + b = -7 $\trinom{4}{1}{3}$ + 1 $\trinom{7}{1}{9}$ = [-21, 6, -12]

# **Q2. Distance**

Let $w_1$ = [4, 3] and $w_2$ = [16, 12] ; $w_0^1$ = 3 and $w_0^2$ = 7, x is a vector

Now let equations of 2 lines be:

L1: $w_1$.x + $w_0^1$ = 0

L2: $w_2$.x + $w_0^2$ = 0

What is the distance between them?

#### **Ans**

The two lines are of the form:

L1: [4 3]$\binom{x}{y}$ + 3 = 0 => 4x + 3y + 3 = 0

L2: [16 12]$\binom{x}{y}$ + 7 = 0 => 16x + 12y + 7 = 0

Slope of two lines m = -4/3,

Y-intercepts $C_1$ = -1 and $C_2$ = -7/12

Distance between lines = (-7/12 + 1)/$\sqrt{1+(-4/3)^2}$

> Using the formula Distance between two parallel lines = |$C_2$ - $C_1$| / $\sqrt{1 + m^2}$

= (5/12)/$\sqrt{25/9}$
= 5/12*3/5 = 1/4

# **Q3. Unit vector angle**

Let a and b be two unit vectors. If the vectors **c = a + 2b** and **d = 5a − 4b** are perpendicular to each other, then the angle (in radians) between a and b is?

#### **Ans:**

Since vectors **c** and **d** are perpendicular to each other, **c.d = 0**

(a + 2b).(5a - 4b) = 0

=> 5$a^2$ + 10ab - 4ab -8$b^2$ = 0

=> 5 + 6ab - 8 = 0 (as $a^2$ = $b^2$ = 1)

=> a.b = 3/6 = 1/2

=>|a||b|cos$\theta$ = 1/2

=> cos$\theta$ = 1/2 (as |a| = |b| = 1)

=> $\theta$ = $\pi$/3 radians or $60^0$

# **Q4. Updated Equation**

Let $x_i$ be a datapoint with respect to ground truth label $y_i$.

Which of the following is the correct updated equation for w?

The ground truth label of a point is +1 if the point lies in the positive halfspace and -1 if it lies in the negative halfspaces of the plane.

The coefficients of an equation are updated using the following rules:

1. If a label 1 datapoint is misclassified in prediction, we will update w using w = w + x, and

2. If a label -1 datapoint is misclassified in prediction, we will update w using w = w - x, where w is the coefficient vector of the plane and x is the variables vector.

#### **Ans**

if sign($\bar{w}$.$x_i$ + $w_0$) != sign($y_i$): $\bar{w}$ = $\bar{w}$ + $x_i$.sign($y_i$)

# **Q5. Three Biases**

Three lines are represented by weight vectors and biases as follows

L1: ($\bar{w}_1$, $w^1_0$)

L2: ($\bar{w}_2$, $w^2_0$)

L3: ($\bar{w}_3$, $w^3_0$)

Choose the correct answer from below:

a. If $w^1_0$ < 0, $w^2_0$ > 0 and $w^3_0$ > 0, then the origin lies in the positive half space for all lines

b. If $w^1_0$ > 0, $w^2_0$ > 0 and $w^3_0$ < 0, then the origin lies in the positive half space for all lines

c. If $w^1_0$ > 0, $w^2_0$ < 0 and $w^3_0$ > 0, then the origin lies in the positive half space for all lines

d. If $w^1_0$ > 0, $w^2_0$ > 0 and $w^3_0$ > 0, then the origin lies in the positive half space for all lines

#### **Ans:**

d. If $w^1_0$ > 0, $w^2_0$ > 0 and $w^3_0$ > 0, then the origin lies in the positive half space for all lines

# **Q6. Separating plane**

If the label of point(1, 2) is -1. Given that we have a separating plane 4x + 3y - 12 = 0. What is the correct update equation for w ?

We will use the perceptron update rule for updating the coefficients of classifier, which says that:
1. If a label 1 datapoint is misclassified in the given, we will update w using w = w+x
2. If a label -1 datapoint is misclassified, we will update w using w = w - x

where w is the coefficient vector and x is the variables vector.

**Note:** A datapoint should be labelled 1 if $w^T$x + $w_0$ > 0 and -1 if $w^T$x + $w_0$ < 0, where w is the vector consisting of coefficients of variables and $w_0$ is the constant

#### **Ans:**

No update required, because 4 ( 1 ) + 3 ( 2 ) - 12 = -2, which is < 0, so, the classification is correct as well!

# **AQ1. Circle**

Let the equation of circle be $x^2$ + $y^2$ - 3 = 0. Determine the position of the data point [1/2, 3/2] w.r.t the circle.

####**Ans:**

Substituting [1/2, 3/2] into the equation gives:

$(1/2)^2$ + $(3/2)^2$ - 3 = 10/4 - 3 = -1/2 (Which is < 0)

Therefore the point is **inside the bounding circle**!

# **AQ2. Length of the projection**

Let x = [2, 1, -3] and y = [5, 8, 6] be two vectors. What is the length of the projection of x on y?

#### **Ans:**

Projection of x on y = |x|cos$\theta$ = x.y/|y|

= $\trinom{2}{1}{-3}$ . $\trinom{5}{8}{6}$ / $\sqrt{5^2 + 8^2 + 6^2}$

= 0 / $\sqrt{125}$

= 0
"""