# -*- coding: utf-8 -*-
"""Dec24_NP_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YyZuoB1xmMcBh25RnIT5p2rHxx8lsi4
"""

#Importing the numpy library

import numpy as np

#giving the alias np is a general convention

"""#Creating and initializing a numpy array

##Converting an existing Python List into a numpy array
"""

#Converting an existing Python List into a numpy array

list_1 = [0,1,2,3,4,5,6,7,8,9,10]



print(list_1)

print(type(list_1))

a = np.array(list_1) #input: list / tuple / set

print(a)

print(type(a))

print(-a)

#Properties of arr_1

print(a.dtype)

print(a.ndim)

print(a.shape)

print(a.size)

list_2 = [0,1,2,3,4.83,5,6,7,8,9,10]

arr_2 = np.array(list_2)

print(list_2)
print(arr_2)

print(arr_2.dtype)

"""##Other ways to create a numpy array with custom data"""

#Other ways to create a numpy array with custom data

desired_shape = (7,)

arr_zeros = np.zeros(shape = desired_shape)
print(f"The array of shape {desired_shape} initialized with zeros: {arr_zeros} \n")



arr_ones = np.ones(shape = desired_shape)
print(f"The array of shape {desired_shape} initialized with ones: {arr_ones} \n")

arr_randint = np.random.randint(1,5, size = desired_shape) #1 is included; 5 is excluded
print(f"The array of shape {desired_shape} initialized with random integers: {arr_randint} \n")

arr_zeros.dtype

arr_zeros_int = np.zeros(shape=(4,2), dtype='int')

arr_zeros_int

#There are 2 ways of changing existing data types

print(arr_randint)
print(arr_randint.dtype)

print("\nI will now change the dtype of arr_randint\n")
arr_randint = np.array(arr_randint, dtype = "float64")

print(arr_randint)

print(arr_randint.dtype)

# arr_6.astype("float64")

arr_6 = np.array([1,2,3])

arr_6 = arr_6.astype("float64")

print(arr_6)

#How do you create a list with numbers from 1 to 75

#for i in range(1,75+1)

arr_10 = np.arange(1,75+1)

print(arr_10)

#How do you create a list with only ODD numbers from 1 to 75

#for i in range(1,75+1, 2)

arr_11 = np.arange(1,75+1, 2)

print(arr_11)

"""#Indexing and Slicing"""

arr = np.array(
                [
                    [0, 1, 2],
                    [3, 4, 5],
                    [6, 7, 8],
                    [9,10,11]
                ])
#print(arr.shape)

#Print the value '2' from the array
#print(arr[0,2])


#First row of the array
#print(arr[0])


#print columns
print(arr[:,:])

print(arr[:, 2])


#arr[row_index , col_index]
#arr[row_slice, col_slice]

b = np.array([10,20,30,40,50,60,70])

print(b[0:2+1])

#from b, print [50,60,70]

print(b[4:])

"""Passing a LIST of indexes"""

x = np.array([0, 10, 20, 30, 40, 59, 68, 74, 100])

list_of_indexes = None

new_shape = (3,3)

y = x.reshape(new_shape)

print(y)

"""#Filtering"""

value = np.array([54, 36, 11, 7, 45, 100, 18, 25, 26, 30])


#value > 25

#This is how filters can be applied

#Can I shorten the above code

"""#In-class Quizzes"""

#Q1
#What will be the output of the following code?
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

#Q2

#What will be the output of the following code?
import numpy as np
arr = np.arange(5)

print(f"Before modification = {arr}\n\n")


arr[2:4] = 0

print(f"After modification = {arr}")

"""#Airbnb NPS data"""

#Download Airbnb's nps "survey" data (.txt format)
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

#Load the nps survey data into a numpy array named 'airbnb_nps'
airbnb_nps = np.loadtxt("survey.txt", dtype=int)


print(f"\nTask completed: Survey data loaded into a numpy array named 'airbnb_nps'")

#Let's view the contents of the array

print(airbnb_nps)

#ndim = 1
#shape = ()

#stype, ndim, shape, size of array

print(f"Datatype of airbnb_nps array = {airbnb_nps.dtype}")
print(f"\nNumber of Dimensions in airbnb_nps array = {airbnb_nps.ndim}")
print(f"\nShape of airbnb_nps array = {airbnb_nps.shape}")
print(f"\nSize of airbnb_nps array = {airbnb_nps.size}")

#Identify Promoters, Detractors, Neutrals

promoters = None #use special numpy filters to generate an array of promoters only

detractors = None #use special numpy filters to generate an array of detractors only

print(f"Insights from the Airbnb NPS survey data: \n")

print(f"number of promoters = {promoters.size}")
print(f"number of detractors = {detractors.size}")
print(f"number of survey respondents = {airbnb_nps.size} \n")

percentage_promoters = (promoters.size / airbnb_nps.size) * 100
percentage_detractors = (detractors.size / airbnb_nps.size) * 100
print(f"% of promoters = {percentage_promoters : .2f}")
print(f"% of detractors = {percentage_detractors : .2f} \n")

print(f"NPS score from the airbnb survey = {percentage_promoters - percentage_detractors : .2f}")

"""#-----------------------------------------------------

#-----------------------------------------------------

# [OPTIONAL]: Use cases of numpy in handling image data

##Creating a simulation of a 4k resolution image data (black and white)

##### NOTE: This simulation is completely OPTIONAL
##### and beyond the scope of today's intro session
##### Feel free to skip this block of code, if it's confusing at any point

###Part A: Creating a 4k image data using random values from 0-255
"""

#Random 4k image data using a Python List

import random

row_pixels = 2160
col_pixels = 3840

img_list = []

for row_no in range(row_pixels):
  temp_row = []
  for col_no in range(col_pixels):
      new_random_val = random.randint(0, 255) #Both 0 and 255 included
      temp_row.append(new_random_val)
  img_list.append(temp_row)

print(f"Task Completed: Random img_list created with {row_pixels} x {col_pixels} values")

#print(img_list) #Warning! Colab will not be able to display 8.3 million elements in Output

#Snapshot of img_list:
#Displaying only the top-left 10x10 values from img_list

print(f"no of rows in img_list = {len(img_list)}")
print(f"no of columns in img_list = {len(img_list[0])}")
print(f"no of elements in img_list = {len(img_list) * len(img_list[0])}")

print(f"\nDisplaying only the top-left 10x10 values from list: \n")

print(f"[")
for row_no in range(10):
  print(f"   {img_list[row_no][:10]} ...")
print(f"   ...\n   ...")
print(f"]")

"""```
Now let's create a numpy array...

```
"""

#Creating a similar 4k img (random) data using a numpy array

img_arr = np.random.randint(0,255,size=(row_pixels,col_pixels)) #NOTE: the end_val 255 is excluded here

print(img_arr) #Let's try to display the full array

print(img_arr.shape)

print(img_arr.shape[0])

print(img_arr.shape[1])

print(img_arr.ndim)

"""###Part B: Updating brightness of each pixel by +25 units:"""

#Updating the python list with +25 brightness for each value

import time

#Let's first create a deep copy of the img_list
import copy
img_list_copy = copy.deepcopy(img_list)

#Let's calculate time taken for updating all elements of img_list by +25
start_time = time.time()  #Noting the timestamp just before the update

for row_no in range(row_pixels):
  for col_no in range(col_pixels):
    img_list_copy[row_no][col_no] = img_list_copy[row_no][col_no] + 25

end_time = time.time()    #Noting the timestamp just after the update

#print(f"{img_list}")

print(f"Time taken for img_list update = {end_time - start_time : .3f} seconds")

#Updating the numpy array with +25 brightness for each value

import time

#Let's first create a copy of the img_list
img_arr_copy = img_arr

#Let's calculate time taken for updating all elements of img_arr by +25
start_time = time.time()
img_arr_copy = img_arr_copy + 25
end_time = time.time()

print(f"updated img_arr:\n{img_arr_copy}")

print(f"\n\nTime taken for img_arr update = {end_time - start_time : .3f} seconds")

2.096 / 0.033

"""##--------------------------------

##Actual 2d data that holds the (black and white) image of birds

##### NOTE: This simulation is completely OPTIONAL
##### and beyond the scope of today's intro session
##### Feel free to skip this block of code, if it's confusing at any point
"""

#download file with "birds" image data
!gdown 1UL59W-QUysWJ_QtJMx0Wdj30g0Qcu8LR


#Importing another library for handling images in Python
import matplotlib.pyplot as plt

#Load the data into a 2d numpy array
birds_img_arr = plt.imread("birds.jpeg")

print(f"\nTask completed: Birds image data loaded into the array 'birds_img_arr'")

#How many rows and columns are there in the birds_img_arr?

print(f"No of dimensions in birds_img_arr = {birds_img_arr.ndim}")
print(f"Shape of birds_img_arr = {birds_img_arr.shape}\n")
print(f"no of rows in birds_img_arr = {birds_img_arr.shape[0]}")
print(f"no of cols in birds_img_arr = {birds_img_arr.shape[1]}") #len of first row
print(f"no of elements in birds_img_arr = {birds_img_arr.shape[0]} * {birds_img_arr.shape[1]} = {(birds_img_arr.shape[0]) * (birds_img_arr.shape[1])}")



print(len(birds_img_arr))

#Displaying the data contained in the birds_img_arr

print(birds_img_arr)

birds_img_arr = birds_img_arr + 75

#Plotting the birds_img_arr data

plt.title("Plotting the pixel data of birds_img_arr:")
plt.imshow(birds_img_arr, cmap='gray')
plt.show()

plt.imshow(birds_img_arr[ :, 0:384], cmap='gray')
plt.show()

plt.imshow(birds_img_arr[ :400, 0:384], cmap='gray')
plt.show()

plt.imshow(birds_img_arr[ : : 2, : : 2], cmap='gray')
plt.show()

birds_img_arr.shape

768/2

birds_img_arr[ :, 0:384]

arr_75 = np.array([10,20,30,40,50,60,70,80,90,100])

print(arr_75[ 3: : 2])



#arr_75[ start: stop: step]

"""###Brightening the birds image"""

#Plotting the birds_img_arr data after brightening by +75


additional_brightness = 75

#Update pixels by +75, and also ensuring the new element value is "capped at 255"
updated_birds_img_arr = np.where(birds_img_arr <= (255 - additional_brightness),   #if updated_val WILL BE < upper_limit
                                 birds_img_arr + additional_brightness,            #then update as desired
                                 255)                                              #else, cap the update at upper_limit

plt.title(f"All pixels of birds_img_arr brightened by +{additional_brightness}:")
plt.imshow(updated_birds_img_arr, cmap='gray')
plt.show()

