# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9YR2xL3cGauDssWmcJ1XNPiJG0MplfT

$\newcommand{\trinom}[3]{\begin{pmatrix} #1 \\ #2 \\ #3 \end{pmatrix}}$

# **Q1. Add padding**

**Problem statement:**

Given a NumPy array of shape (n,m). Add padding of a layer of 0’s on all 4 boundaries of the matrix.

**Sample Input:**

````
3 2  
1 2  
3 4  
5 6
````

**Sample Output:**

````
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 5 6 0]
 [0 0 0 0]]
````
"""

import numpy as np

def add_padding(mat):
    '''mat-> NumPy array
       output-> NumPy array is expected to be returned'''

    # YOUR CODE GOES HERE

    res = None
    h_zero_paddings = np.zeros((mat.shape[0], 1), dtype=int)
    mat_h_padded = np.hstack([h_zero_paddings, mat, h_zero_paddings])
    v_zero_paddings = np.zeros((1, mat_h_padded.shape[1]), dtype=int)
    res = np.vstack([v_zero_paddings, mat_h_padded, v_zero_paddings])

    return res

mat = np.array([[3,2],[1,2], [3, 4], [5, 6]])
print(mat)
print(f"""
add_padding(mat)=
{add_padding(mat)}
""")

"""# **Q2. Column split**

Given an MxN 2D array (M >= 4),

Split the array column wise such that,

1. 1st sub array contains the first 2 columns
2. 2nd sub array contains the 3rd column
3. 3rd sub array contains the rest of the columns

**Sample Input:**

```
[[0, 1, 2, 3],
 [4, 5, 6, 7],
 [8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19],
 [20, 21, 22, 23]]
```

**Sample Output:**

```
[
array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]),
array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]]),
array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])]
```
"""

import numpy as np

def split(arr):
    '''
    INPUT: arr -> 2D array

    OUTPUT: subarrays -> list of 2D arrays
    '''

    subarrays = None
    hsplit_idx = [2, 3]
    subarrays = np.hsplit(arr, hsplit_idx)

    return subarrays

arr = np.arange(24).reshape(6, 4)
print(f"""
arr =
{arr}

split(arr) =
{split(arr)}
""")

"""# **Q3. Split second**

**Problem statement:**

Given an 1D array and an integer k that specifies the number of equal parts to split the array into,

Perform the following operations:

1. Split the array into k number of equal parts.
2. Return the list of split arrays.

**Assumption:** The array can be split into k equal parts

**Note:** Recall how to split an array into equal parts.

**Sample Input:**

```
arr = [0,1,2,3,4,5,6,7,8]
k = 3
```

**Sample Output:**

```
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
```
"""

import numpy as np

def split(arr, k):
    '''
    INPUT: arr, k

    OUTPUT: split_arr -> list of arrays
    '''

    split_arr = None

    ## CODE starts here
    split_arr = np.split(arr, k)


    return split_arr

arr = np.arange(9)
k = 3
print(f"""
arr = {arr}
k = 3
split(arr, k) =
{split(arr, k)}
""")

"""# **Q4. Q4. Wise split**

What will be the output of following code?

```python
import numpy as np
arr = np.arange(16).reshape(4,4)  
print(np.split(arr,4))
```

A.

Error

B.

```
[array([[ 0, 4, 8, 12]]),
 array([[ 1, 5, 9, 13]]),
 array([[ 2, 6, 10, 14]]),
 array([[ 3, 7, 11, 15]])]
```

C.

```
[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8, 9, 10, 11]]),
 array([[12, 13, 14, 15]])]
```

D.

```
[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]
```

#### **Ans:**

Option C:

```
[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8, 9, 10, 11]]),
 array([[12, 13, 14, 15]])]
 ```
"""

import numpy as np
arr = np.arange(16).reshape(4,4)
print(np.split(arr,4))

"""# **Q5. Filter Copy**

Which of the following will return a deep copy of array?

```python
arr = np.array([1,2,3,0,-2,4])
```

```
A. arr1 = arr*1
B. arr1 = arr[:]
C. arr1 = arr[arr > 0]
D. arr1 = arr.reshape(2,3)
```

####**Ans:**

Options A & C:

```
arr1 = arr*1
arr1 = arr[arr > 0]
```
"""

import numpy as np

arr = np.array([1,2,3,0,-2,4])

arr1 = arr*1
print(np.shares_memory(arr1, arr))
arr1 = arr[:]
print(np.shares_memory(arr1, arr))
arr1 = arr[arr > 0]
print(np.shares_memory(arr1, arr))
arr1 = arr.reshape(2,3)
print(np.shares_memory(arr1, arr))

"""# **Q6. Inter dimension**

Given a 3D array of shape (2, 3, 3)

```
array([[[ 0, 1, 2],
        [ 3, 4, 5],
        [ 6, 7, 8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])
```

What will be the output of arr[1, :, :] ?

A.

```
array([[ 3, 4, 5],
       [12, 13, 14]])
```

B.

```
array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])
```

C.

```
array([[ 1, 4, 7],
       [10, 13, 16]])
```

D.

```
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

#### **Ans:**
Option B:

```
array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])
```
"""

import numpy as np
arr = np.array(
    [[[ 0, 1, 2],
        [ 3, 4, 5],
        [ 6, 7, 8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])
print(arr[1, :, :])

"""# **Q7. Hstack**

aw Problem

Given the following code, what will be the output of the final line?

```python
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(np.hstack((arr, arr[:, [0]])).shape)
```

**Note:** np is the alias for NumPy in the options.
"""

arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(np.hstack((arr, arr[:, [0]])).shape)

"""# **AQ1. Stack up**

Which of the following is used to stack arrays column wise?

1. hsplit()
2. vsplit()
3. hstack()
4. vstack()

#### **Ans:**

Option 3: hstack()

# **AQ2. Split the difference**

Which of the following code snippet will raise an error?

A.

```python
arr = np.arange(10)
np.split(arr, 3)
```

B.

```python
arr = np.arange(10)
np.split(arr, 5)
```

C.

```python
arr = np.arange(10)
np.split(arr, [2,5])
```

D.

```python
arr = np.arange(10)
np.split(arr, [5, 12])
```

#### **Ans:**
Option A:

```python
arr = np.arange(10)
np.split(arr, 3)
```

**Explanation:** The split call in Option A tries to split array of size 10 into 3 equal pieces which is not possible, so, python will raise `ValueError: array split does not result in an equal division`

# **AQ3. Row vs column**

Given a 2D array, which of the following will split the array **row-wise**?

1. hsplit()
2. vsplit()
3. hstack()
4. vstack()

#### **Ans:**

Option 2: vsplit()

# **AQ4. Copy types**

```python
import numpy as np
arr = np.array([2, 4, 6, 8, 10])
c0 = arr
c0[0] = 12
arr = np.array([2, 4, 6, 8, 10])
c1 = arr.view()
arr[0] = 12
arr = np.array([2, 4, 6, 8, 10])
c2 = arr.copy()
arr[0] = 12
```

According to the above code snippet, which two options are correct?

1. c1 represents shallow copy and c2 represents deep copy
2. c1 represents deep copy and c2 represents shallow copy.
3. If arr and c1 are printed after line 4 and 7 respectively, they would have printed 12 as first element.
4. If c1 and c2 are printed after line 7 and 10 respectively, they would print 12 as first element of array.

#### **Ans:**

Options 1 & 3:

* c1 represents shallow copy and c2 represents deep copy
* If arr and c1 are printed after line 4 and 7 respectively, they would have printed 12 as first element.

# **AQ5. Dark dimension**

Given a 3D array of shape (2,2,2)

```
arr = array([[[0, 1],
             [2, 3]],

            [[4, 5],
             [6, 7]]])
```

What will be the output of arr[:, 0:,:1]?

A.

```
array([[2, 3],
       [6, 7]])
```

B.

```
array([[0, 1],
       [4, 5]])
```

C.

```
array([[[0],
        [2]],

       [[4],
        [6]]])
```

D.

```
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
```

#### **Ans:**

Option C:

```
array([[[0],
        [2]],

       [[4],
        [6]]])
```

# **AQ6. Split and cycle**

You are given the following:

A 2D Numpy array (data) representing a grayscale image, where pixel values range from 0 (black) to 255 (white).
A desired number of horizontal splits (num_splits).

**Tasks:**

1. Split the image to divide the image array (data) evenly into num_splits horizontal sections.
2. Rearrange sections: Create a new array by concatenating the image sections in the following order:
    * The last section moves to the first position.
    * All other sections shift downwards by one position.
3. Return the modified array

**Input Sample**

```
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])

num_splits = 2
```

**Output Sample**

```
[[ 70  80  90]
 [100 110 120]
 [ 10  20  30]
 [ 40  50  60]]
```
"""

def rearrange_image(data, num_splits):
    # write your code here
    data_v_splits = np.vsplit(data, num_splits)

    last_element = data_v_splits.pop()
    data_v_splits.insert(0, last_element)

    # return the modified array as per instructions.
    return np.vstack(data_v_splits)

data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])

num_splits = 2
data_rearranged = rearrange_image(data, num_splits)
print(data_rearranged)