# -*- coding: utf-8 -*-
"""Dec24_NP_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BjR0iuGNv2Pvc-_VwT3KSyxfSq4z_bd8
"""

#Importing the numpy library

import numpy as np

"""#Copying Arrays"""

#I will make several copies of an original array named "a"

a = np.array([15,30,45,60])

a2 = a  #this is technically not a "copy"

a3 = a[:] #slicing

a4 = a.copy() #copy function WILL CREATE DEEP copies for ANY array with NUMBERS

a5 = np.array(a) #array function

a6 = a[a > 0] #masking and filtering

a7 = a.reshape(a.shape) #reshape function


print(f"a = {a} \n")
print(f"a2 = {a2} \n")
print(f"a3 = {a3} \n")
print(f"a4 = {a4} \n")
print(f"a5 = {a5} \n")
print(f"a6 = {a6} \n")
print(f"a7 = {a7} \n")

#Is it possible to figure out if the above copies are SHALLOW / DEEP

#np.shares_memory(arr1, arr2)

print(f"np.shares_memory(a, a2) =  {np.shares_memory(a, a2)} \n")
print(f"np.shares_memory(a, a3) =  {np.shares_memory(a, a3)} \n")
print(f"np.shares_memory(a, a4) =  {np.shares_memory(a, a4)} \n")
print(f"np.shares_memory(a, a5) =  {np.shares_memory(a, a5)} \n")
print(f"np.shares_memory(a, a6) =  {np.shares_memory(a, a6)} \n")
print(f"np.shares_memory(a, a7) =  {np.shares_memory(a, a7)} \n")

#What happens if I manipulate some value in the original array "a"

a[0] = 999 #[15, 30, 45, 60] ---> [999, 30, 45, 60]

print(f"a = {a} \n")
print(f"a2 = {a2} \n")
print(f"a3 = {a3} \n")
print(f"a4 = {a4} \n")
print(f"a5 = {a5} \n")
print(f"a6 = {a6} \n")
print(f"a7 = {a7} \n")

"""View"""

array_c = np.array(
                    [
                      [15, 30, 45, 60],
                      [ 1,  2,  3,  4],
                      [99, 88, 77, 66]
                    ]
                  )

view_of_c_middle_row = array_c[1].view()

print(f"array_c   = \n{array_c} \n")
print(f"view_of_c_middle_row = \n{view_of_c_middle_row} \n")

"""#Retrieving the birds image"""

#download file with "birds" image data
!gdown 1UL59W-QUysWJ_QtJMx0Wdj30g0Qcu8LR


#Importing another library for handling images in Python
import matplotlib.pyplot as plt

#Load the data into a 2d numpy array
birds_img_arr = plt.imread("birds.jpeg")

print(f"\nTask completed: Birds image data loaded into the array 'birds_img_arr'")

#How many rows and columns are there in the birds_img_arr?

print(f"No of dimensions in birds_img_arr = {birds_img_arr.ndim}")
print(f"Shape of birds_img_arr = {birds_img_arr.shape}\n")
print(f"no of rows in birds_img_arr = {birds_img_arr.shape[0]}")
print(f"no of cols in birds_img_arr = {birds_img_arr.shape[1]}") #len of first row
print(f"no of elements in birds_img_arr = {birds_img_arr.shape[0]} * {birds_img_arr.shape[1]} = {birds_img_arr.size}")

#Displaying the data contained in the birds_img_arr

print(birds_img_arr)

#Plotting the birds_img_arr data


plt.title("Plotting the pixel data of birds_img_arr")
plt.imshow(birds_img_arr, cmap='gray')
plt.show()

#BREAK! Resuming at 10:12 PM IST

"""#Vertical Splitting and Stacking"""

#I want to V split birds_img_arr into n EQUAL pieces

n = 2

v_pieces = np.vsplit(birds_img_arr, n)

len(v_pieces)

#Let's examines the first piece

print(f"Shape of birds_img_arr = {birds_img_arr.shape}\n")
print(f"v_pieces[0].shape = {v_pieces[0].shape}")
print(f"v_pieces[1].shape = {v_pieces[1].shape}")

#Let's plot the first piece

plt.imshow(v_pieces[0], cmap='gray')
plt.show()

#Let's plot the second piece

plt.imshow(v_pieces[1], cmap='gray')
plt.show()

#Vertically stack the pieces

list_of_pieces = [v_pieces[1], v_pieces[0]]

#np.vstack(list_of_pieces)

plt.imshow(np.vstack(list_of_pieces), cmap='gray')
plt.show()

"""#Horizontal Splitting and Stacking"""

h_pieces = np.hsplit(birds_img_arr, 2) #cut into 2 equal pieces

#Let's make the birds "face each other"

#Let's make it face the right direction
plt.title("Left side bird ->> facing right")
plt.imshow(h_pieces[0][::,::-1], cmap='gray')
plt.show()

#Second bird


plt.title("Right side bird")
plt.imshow(h_pieces[1], cmap='gray')
plt.show()

#Let's stack the birds horizontally and make them face each other

h_stack_order = [ h_pieces[0][::,::-1], h_pieces[1]]

new_birds_img = np.hstack(h_stack_order)

plt.title("Birds facing each other")
plt.imshow(new_birds_img, cmap='gray')
plt.show()





"""#Horizontal split with unequal pieces

"""

#Plotting the birds_img_arr data


plt.title("Plotting the pixel data of birds_img_arr")
plt.imshow(birds_img_arr, cmap='gray')
plt.show()

#I want 7 pieces ---> 6 cuts

cuts = [100, 200, 300, 400, 500, 600]

birds_img_pieces = np.hsplit(birds_img_arr, cuts)

my_custom_stack_order = [birds_img_pieces[1], birds_img_pieces[2]]

plt.imshow(np.hstack(my_custom_stack_order), cmap="gray")
plt.show()

len(birds_img_pieces) #indexes = 0, 1, 2, .... 6

len

no_of_cuts = 6

list_of_indexes_to_cut_at = [100,200,300,400,500,600]

pieces = np.hsplit(birds_img_arr, list_of_indexes_to_cut_at)

plt.imshow(pieces[6], cmap='gray')
plt.show()



"""#Printing of arrays with dimensions > 2"""

#1D array is an array of 0D elements

k1 = 15
k2 = 34
k3 = 99

a_1D = np.array([k1,k1,k3]) #1D array: array of scalar values

print(a_1D.shape)
print()
print(a_1D) #SINGLE axis: axis = 0

#2D array: an array of 1D elements

x = [1,3,4,6]
y = [3,4,5,6]
z = [9,3,21,23]


arr_2D = np.array([ x, y , z]) #2D array: array of 1D elements

print(arr_2D)

#3D array: an array of 2D elements

t = [
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
]

u = [
    [5,5,5,5],
    [5,5,5,5],
    [5,5,5,5]
]


v = [
    [9,9,9,9],
    [9,9,9,9],
    [9,9,9,9]
]


arr_3D = np.array([ t, u, v]) #3D array: array of 2d elements

print(len(t))
print(np.array(t).shape)
print(arr_3D.shape)

print(arr_3D)

"""#Is Broadcasting possible?"""

a = [5,6,7]
a = np.array(a)

b = [[1,1,1],
     [2,2,2],
     [3,3,3]]
b = np.array(b)

print(a+b)

x = [5,6,7]
x = np.array(x)

y = [[1,1,1,1,1],
     [2,2,2,2,2],
     [3,3,3,3,3]]
y = np.array(y)

print(x+y)

w = np.array([
    [10,20,30,40]
])

v= np.array([
    [5],
    [6],
    [7],
    [8]
])

print(w.shape, v.shape)

print(w+v)

"""#In class quizzes"""

#Q1

"""
a = [0,1,2,3,4,5]
b = a[a%1 == 0] #filter to create copy
b[0] = 10
a[:2] = ?
"""


a = np.array([0,1,2,3,4,5])
print(a)
print()

b = a[a%1 == 0]
print(b) #Deep copy of a -> a new object
print()

a[0] = 10 #this affects only b
print(a)
print(b)
print()

print(a[:2])

#Q2

"""
What will be the output of following code?
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a, b))
"""


a = np.array([[1], [2], [3]])
print(a)
print()
b = np.array([[4], [5], [6]])
print(b)
print()

print(np.vstack((a, b)))

#Q3

"""
What will be the output of following code?
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.hstack((a, b))
"""

a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
print(a, end = "\n\n")
print(b, end = "\n\n")
print(np.hstack((a, b)))

x = np.array([[1,100,300,400], [2,200,300,400], [3,0,0,0]])
y = np.array([[4], [5], [6]])

print(x.shape)
print(y.shape)

np.vstack([x,y])

np.hstack([x,y])



"""#Colour image of fox"""

#download fox image (colour)

!gdown 1ER2L_ae3mcW90Pe_zsuaXNOlR4VSKCop

fox = plt.imread("fox_colour.jpeg")

fox.ndim

fox.shape

#printing the 3d image

plt.imshow(fox)
plt.show()

