# -*- coding: utf-8 -*-
"""Netflix Intro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14P5am2ltkFme0r0hGVaStinXECEYQT6_

# Problem Statement:

What type of Shows/Movies to Produce and how to grow business in different countries.
"""

# Import relevant Libraries:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Load the data
df = pd.read_csv('netflix.csv')

# Let's look at the sample rows
df.sample(5)

# 1. No. of rows and columns
print(df.shape)

# 2. Basic Info: Column names, column data type, number of non-null values
print(df.info())

# 3. Percentage of null values
df.isnull().sum() * 100 / len(df)

df['type'].value_counts()

"""### Insights:
1.
2.
3.
"""

df['listed_in'] = df['listed_in'].apply(lambda x : x.split(','))

df.explode('listed_in')['listed_in'].value_counts()

'country' 'TV Shows' | 'Movies'
'US'           12           25

import seaborn as sns # Univariate
sns.countplot(data=df[df['release_year'] > 2015],x='release_year')

# Movie and TV Show
df_movie = df[df['type'] == 'Movie']
df_movie.head()

df_movie['duration_int'] = df_movie['duration'].dropna().apply(lambda x : x[ : -4]).astype('int')

df_movie.head()

"""1.
2.
"""

df_movie.groupby('country')['duration_int'].describe()

df['country'].unique()

q3 = df_movie['duration_int'].quantile(0.75)
q1 = df_movie['duration_int'].quantile(0.25)

iqr = q3-q1

ub = q3 + 1.5*iqr
lb = q1 - 1.5*iqr


df_movie[(df_movie['duration_int'] > lb) & (df_movie['duration_int'] < ub)]['duration_int'].describe()

ub, lb

import pandas as pd

# Example data
data = {'City': ['New York', 'London', 'Tokyo', 'New York', 'Tokyo', 'London']}
df = pd.DataFrame(data)

df.info()

df['City'].astype('category')

df.info()

df['Size'] = ['Small', 'Medium', 'Large', 'Small', 'Medium', 'Large']

df # small < medium < larged

df['Size'] = df['Size'].astype('category').cat.set_categories(['Small', 'Medium', 'Large'], ordered=True)

df[df['Size'] > 'Small']

df[col].str