# -*- coding: utf-8 -*-
"""Dec24_NP_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYhStmuyYcLCNBeSQd93KclUFnCP_bjU
"""

#import necessary libraries

import numpy as np

"""#Aggregate functions

* np.sum()
* np.mean()
* np.median()
* np.min()
* np.max()

##Aggregate functions on 1D arrays
"""

array_1 = np.zeros(shape=(15,))
print(array_1)
print()

array_2 = np.ones(shape=(15,))
print(array_2)
print()


array_3 = np.random.randint(low=0, high=100, size = (15,))
print(array_3)
print()



#range(start, stop, step) ----> np.arange(start,stop,stop)
array_4 = np.arange(10, 24+1)
print(array_4)
print()

#sum of numbers
print("sum =",np.sum(array_2))
print()
print(array_2)

#sum of numbers
print("max =",np.max(array_3))
print()
print("min =",np.min(array_3))
print()

#alternate approach

array_3.min()

"""##Aggregate functions on 2D arrays"""

arr_2d = np.array(
                    [
                       [  1,  2,    3],
                       [ 10, 20,   30],
                       [100, 200, 300],
                       [  1,   1,   1]

                    ]

)

print(arr_2d)

print(np.sum(arr_2d))

#row sums

print(np.sum(arr_2d, axis=1))

#column sums

print(np.sum(arr_2d, axis=0))

"""#Sorting

##Sorting a 1D array
"""

#Sorting a 1D array

array_1 = np.array([15,18,7,24,-21,22,8,-10,11])


#np.sort()

print(array_1)
print()
print(np.sort(array_1))
print()
print(array_1)

#arr_obj.sort()


array_2 = np.array([15,18,7,24,-21,22,8,-10,11])


print(array_2)
print()
print(array_2.sort())
print()
print(array_2)

#Sorting in DESC order

#Method 1

print(array_1)
print()
print(np.sort(array_1)[::-1]) #reversing the result

#Another method of sorting

print(array_1)
print()
print(-array_1)
print()
print(np.sort(-array_1))
print()
print(-np.sort(-array_1))

"""##Sorting a 2D array"""

#2D array

lst_2d = [
    [5,    -7,   46],
    [19,   88,   81],
    [-10, -50,    0],
    [1,     2,    3]
]

arr_2d = np.array(lst_2d)

print(arr_2d)

#We will do a simple sort of the above 2d array

print(np.sort(arr_2d))

#observation: For 2d arrays, the default axis = 1

#strictly speaking: the default axis = -1

#column wise sorting, along axis = 0

print(np.sort(arr_2d, axis=0))

#sort the above 2d array along axis = 1

#sort the above 2d array along axis = 0

#axis = None
#It first flattens the 2d array, and then sorts the flattened array

print(np.sort(arr_2d, axis=None))

shape_of_array = arr_2d.shape

flattened_arr_2d = arr_2d.flatten()

sorted_flattened_arr_2d = np.sort(flattened_arr_2d)

print(sorted_flattened_arr_2d.reshape(shape_of_array))

"""##argsort() : used to sort the indexes"""

marks = np.array([67, 33, 60, 55, 100, 90, 78])

names = np.array(['A','B','C','D','E','F','G'])



"""argmax()"""

#argmax()

marks = np.array([67, 33, 60, 55, 100, 90, 78])

names = np.array(['A','B','C','D','E','F','G'])

print(np.argmax(marks))

#name of the person with the highest marks

#argmin()

marks = np.array([67, 33, 60, 55, 100, 90, 78])

names = np.array(['A','B','C','D','E','F','G'])

"""#Multiplication"""

#multiplying two vectors

a = np.array([5,7,10])
b = np.array([10,100,1000])

print(a*b)

#Can I do this?


a2 = np.array([5,7,10])
b2 = np.array([10,100,1000,55,99])

print(a2*b2)

#multiply a with a scalar (not SCALER) value of 5

print(a*5)

#Let's take another two arrays

c = np.array([5,10])
d = np.array([1,2,3,4])

print(c*d)

"""Element-wise multiplication of matrices"""

m1 = np.array([
                [1, 2],
                [3, 4]
             ])


m2 = np.array([
                [10, 1],
                [5, 55]
             ])

print(m1)
print()
print(m2)
print()
print(m1 * m2)

"""Multiply Vector / Matrix with Scalar"""

v = np.arange(1,6) #vector

s = 100 #scalar

print(v)

print(v*s)



"""#Vectorization

##How vectorization works
"""



"""##Converting legacy functions to work on numpy arrays

* np.vectorize( )
"""

#Custom fuction that takes a number
#and rounds it to the nearest integer

def round_to_integer(x):

  if x >= 0:  #if the input is non-negative

              decimal_part_of_x = x - int(x)

              if decimal_part_of_x >= 0.5:
                return int(x)+1

              else:
                return int(x)

  elif x < 0: #if the input is negative

              decimal_part_of_x = -(x - int(x))

              if decimal_part_of_x >= 0.5:
                  return int(x)-1

              else:
                return int(x)

#Testing the round_to_integer() function

x1 = 32.49
print(f"{x1} after rounding: {round_to_integer(x1)}")
print()

x2 = -5.6
print(f"{x2} after rounding:  {round_to_integer(x2)}")
print()


x3 = np.array([98.6, 98.8, 98.1, 98.4])
print(f"{x3} after rounding: {round_to_integer(x3)}")
print()

"""Fahrenheit to Celcius"""

#Custom fuction that takes a temp value in deg_Fahrenheit
#and returns the corresponding value in deg_Celcius

def fahrenheit_to_celcius(temp_F):
  return (temp_F - 32) * (5/9)

#Testing the fahrenheit_to_celcius() function

t1 = 32
print(f"{t1} deg_F = {fahrenheit_to_celcius(t1)} deg_C")
print()

t2 = -5.6
print(f"{t2} deg_F = {fahrenheit_to_celcius(t2)} deg_C")
print()

t3 = np.array([98.6, 98.8, 98.1, 98.4])
print(f"{t3} deg_F = {fahrenheit_to_celcius(t3)} deg_C")
print()



"""#Broadcasting"""

a = np.array([1,2,3])

print(a+10)

a = np.array([1,2,3]) #shape of a = (3,)

b = np.array([10,20]) #shape of b = (2,)

print(a+b)

def func(x, y):
    return x * y


arr_1 = np.array([
                    [ 2,  3,  4,  5],
                    [ 1,  7,  3,  5],
                    [ 2,  8,  6,  9],
                    [11, 23, 12, 19]
                  ])
#shape of arr_1 = (4,4)



arr_2 = np.array([
                    [2,2,2,2]
                  ])

#shape of arr_2 = (1,4)

func(arr_1,arr_2)



x = np.arange(6).reshape(3,2)

y = np.array([7,9])

print(x.shape)

print(y.shape)

print(x*y) #shape: (3,2)

"""#Q&A segment discussions"""

print(a)
print(np.sum(a[0:9]))
print(np.sum(a))

x1 = [1,2,3]

x2 = [
        [1,2,3]

      ]


x3 = [
        [1],
        [2],
        [3]

      ]


x1=np.array(x1) #1D array
x2=np.array(x2) #2D array
x3=np.array(x3) #2D array

print(x1)
print()
print(x1.shape)

print(x2)
print()
print(x2.shape)

print(x3)
print()
print(x3.shape)

