# -*- coding: utf-8 -*-
"""python_operators_16oct.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a3FOcAw4lMsFvBk4_MmWn_uCmxTljUuq
"""

10 + 3

10 - 3

10 * 3

10/3

10/2

5.0 + 5 # float + float -> float

5 ** 2

5 ** -1

1/5

5 ** 0.5

5.0 ** 2

10//3

-10//3 # floor divistion

10 % 3 # modulus

10 % 3.0

-10//3.0

10%-3

bool(1)

bool(0)

bool(50)

bool(-50)

bool(None)

bool('False')

bool("  ")

bool("")

int(False)

int(True)

my_marks = 80
my_cousin_marks = 90
my_marks > my_cousin_marks

my_marks < my_cousin_marks

my_marks == my_cousin_marks

my_marks = 90
my_marks == my_cousin_marks # sql = is a comparison operator

my_marks != my_cousin_marks

my_marks <> my_cousin_marks # this not-equal to doesn't work in python

# Question - What will be the output?

marks = 50

marks = marks + correction

marks = marks + correction
marks

# Question - What will be the output?

a = 5
a += 2 # a = a + 2
print(a) # 7
a -= 2
print(a) # 5
a *= 2
print(a) # 10

# Question - What will be the output?

a=10
print(a>5 or a>20 or a<2) #True
print(a>5 and a==20 and a<2) #False

# Question - Check if a number is a multiple?

amount = 1000
amount % 500 == 0

# ATM Dispatch for 2 kinds of denominations ( H.W to fix this piece of code)

amount= int(input("Please enter the amount to withdraw: "))
amount % 500 == 0 or amount % 200 == 0 # 900 = 500 + 200 + 200

print(not True)

print(not False)

print(not 24 < 56)

