# -*- coding: utf-8 -*-
"""python_loops_21Oct.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rbq4BM2QgkwtstNE5FVe4HA9rEwYDVc1
"""

while True: # infinite loop
  print("hello")

actual_password = 20
combination = 0 #initialised value

while combination!= actual_password: #check the condition
  print(combination)
  combination+=1 # keep incrementing/chaging

print("unlocked with number: ",combination)

# write a while loop to print numbers from 1-5
num = 1
while num<=5:
  num = num+1
  print(num)

# take an input from the user and print all the alternate numbers from 1 till input
i = 1
val = int(input("Enter the number till which you want to print"))
while i<= val:
  print(i)
  i+=2

#Take an input from the user for start and end values and print every third number.

start = int(input("start "))
end = int(input("end "))

while start<=end:
  print(start)
  start+=3 # start = start + 3

#Take an input from the user for start and end values. Print all even numbers between them.
start = int(input("start "))
end = int(input("end "))
loop_count = 0
while start<=end:
  loop_count += 1
  if start % 2 == 0:
    print(start)
  start = start + 1

print("no of loops: ",loop_count)

# faster code

start = int(input("start "))
end = int(input("end "))
loop_count = 0
while start<=end:
  loop_count += 1
  if start % 2 == 0:
    print(start)
    start+=2
  else:
    start = start + 1

print("no of loops: ",loop_count)

# Quiz
x = 1
while x <= 100:
    if x % 3 == 0 and x % 5 == 0:
        print("FizzBuzz")
    elif x % 3 == 0:
        print("Fizz")
    elif x % 5 == 0:
        print("Buzz")
    else:
        print(x)
    x += 1

#Print all numbers from 1 to N (input from user) in a single line
num = int(input())
i = 1
while i<=num:
  print(i, end="\t")
  i+=1
i = 1
while i<=num:
  print(i, end="<gap>")
  i+=1

# "\t", "\n" : These are escape characters

print(1,2,3,4,5)
print(1,2,3,4,5,sep =",")

print("\\t")

# write code to print table of a number(take number as input)
test_cases = int(input())
t = 1
while t <= test_cases: # try out loop using for instead of while
    number = int(input("Please enter the number: "))
    i = 1
    print("Printing multiplication table of ", number)
    while i <= 10:
        print(number*i, end=" ")
        i += 1
    print("\n")
    t += 1

number = int(input("Please enter the number: "))
i = 1
print("Printing multiplication table of ", number)
while i <= 10:
    print(number*i, end=" ")
    i += 1
print("\n")

int("3")

list(range(1,10)) # 1,2,3,4,5,6,7,8,9

# write range for 3,4,5,6,7
list(range(3,8))

list(range(10))

list(range(-9,-1))

list(range(-1,-9))

list(range(10,1))

list(range(10,1,-1))

list(range(1,10,2))

# print values from 1 to n
number = int(input("Enter a number: "))
for i in range(1,number+1):
  print(i, end=" ")

#Calculate sum of all numbers starting from 1 to N using a for loop
number = int(input("Enter a number: "))
total = 0
for value in range(1,number+1):
  total = total + value
print(total)

# print values from N to 1
number = int(input("Enter a number: "))
for i in range(number,0,-1):
  print(i, end=" ")

# print values from N to 1 ( without using negative jump)
number = int(input("Enter a number: ")) # 10
for i in range(-number,0):
  print(-i, end= " ")

number=int(input())
for value in range(1,number+1): #1, 2
  print(number+1-value) #10 9

range(5)

"""# for sql practice, please refer
1. datalemur
2. leetcode
"""

a = 1
if (a%2!=0):
print("TRUE")

