# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFiyTV_iBdDqUI9_lq-m0EgpPg7EWrf9

**Q1. Date formatting**

**Problem Description:**

Given the input date in **DD/MM/YYYY** format as a string, write a function that returns the converted date in the string formats **MM/DD/YYYY** and **YYYY/MM/DD** and return the new date formats.
"""

def date_format(date):
    '''Input: date takes the string as input
       Output:return resultant date formats'''

    # YOUR CODE GOES HERE
    dd, mm, yyyy = date.split('/')
    return f"{mm}/{dd}/{yyyy}", f"{yyyy}/{mm}/{dd}"

date = "08/12/1998"
print(f"date_format('{date}') = {date_format(date)}")

"""**Q2. Replace Character**

**Problem Description**

You are given a character string **A** and two integer ASCII codes **B** and **C**.

You have to find and replace all the occurrences of the character having ASCII code equal to **B** with character having ASCII code equal to **C** and return the resultant string.
"""

class Solution:

  def solve(self, A, B, C):
    return A.replace(chr(B), chr(C))

solver = Solution()

A = "aabbccbb"
B = 98
C = 100
print(f"Solution().solve('{A}', {B}, {C}) = {solver.solve(A, B, C)}")
A = "abc"
B = 100
C = 97
print(f"Solution().solve('{A}', {B}, {C}) = {solver.solve(A, B, C)}")

"""**Q3. Upper or Lower**

What will be the value of converted_word, if the following operations in the following code snippet are executed?

```python
word = "Scaler Academy"
n = len(word)
word1 = word.upper()
word2 = word.lower()

converted_word = ""

for i in range(n):
     if i % 2 == 0:
          converted_word += word2[i]
     else:
          converted_word += word1[i]
```
"""

word = "Scaler Academy"
n = len(word)
word1 = word.upper()
word2 = word.lower()

converted_word = ""

for i in range(n):
     if i % 2 == 0:
          converted_word += word2[i]
     else:
          converted_word += word1[i]

print(converted_word)

"""**Q4. Reverse the word - II**

**Problem Description**

You are given lowercase string (A) and you have to return after reversing that.
"""

class Solution:
    def solve(self, A):
        return A[::-1]

solver = Solution()

A = "interviewbit"
print(f"Solution().solve('{A}') = {solver.solve(A)}")
A = "scaler"
print(f"Solution().solve('{A}') = {solver.solve(A)}")

"""**Q5. Vowels vs Consonants - II**

**Problem Description**

You are given lowercase string (A) and you have to tell the count of vowels and consonants in it.
"""

VOWELS = "aeiou"

class Solution:
    def solve(self, A):
      alower = A.lower()
      vowel_letters = [letter for letter in alower if letter in VOWELS]
      return [len(vowel_letters), len(A) - len(vowel_letters)]

solver = Solution()

A = "interviewbit"
print(f"Solution().solve('{A}') = {solver.solve(A)}")
A = "scaler"
print(f"Solution().solve('{A}') = {solver.solve(A)}")

"""**AQ1. Brown Fox**

Select the correct output of the following code:

```python
str1 = "quick brown fox word!"
print(str1[12:15], str1[:5], str1[-5:-1], str1[8:110], str1[-4:])
```
"""

str1 = "quick brown fox word!"
print(str1[12:15], str1[:5], str1[-5:-1], str1[8:110], str1[-4:])

"""**AQ2. String Methods**

```python
s = "My PO Box number is 310"

print(s.isalnum())
print(s.islower())
print(s.startswith('My P'))
print(s.isspace())
```
"""

s = "My PO Box number is 310"

print(s.isalnum())
print(s.islower())
print(s.startswith('My P'))
print(s.isspace())

"""**AQ3. 'Hello' Strings**

Which options will raise error if s = "hello"?
"""

s = "hello"
print(s[0:9])
s[2] = 'a'
print(s[9])
print(s[-1])

"""**AQ4. Correct String Operations**

Select the correct output of the following String operations:

```python
str1 = "Hello"
print(str1*2)
```
"""

str1 = "Hello"
print(str1*2)

"""**AQ6. Palindrome or not**

Write a program to check whether the given string is a palindrome or not. Return True if it is palindrome else return False.

**Note:** A string is said to be a palindrome if the reverse of the string is the same as the string itself.
"""

def isPalindrome(s, ignore_case = False):
    '''Input: s takes the string as input
       Output:return the True or False'''
    # YOUR CODE GOES HERE
    # Optional: check and convert the string to lower case if ignore case
    if ignore_case:
        s = s.lower()
    return s == s[::-1]

s = "madam"
print(f"isPalindrome('{s}') = {isPalindrome(s)}")
s = "Level"
print(f"isPalindrome('{s}', True) = {isPalindrome(s, True)}")
s = "hello"
print(f"isPalindrome('{s}') = {isPalindrome(s)}")