# -*- coding: utf-8 -*-
"""python_14oct.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KjAdOeWDG8xTpkEK80XxhOqwXhMiZpT5
"""

print(3000)

print(20+30)

print(4  +    5)

print("India won the world cup in 2024")

print('India won the world cup in 2024')

PRINT("will this work?") # python is case sensitive

print(4 < 3)

print("Hello class')

type(.2)

type(2.)

type(2)

type("2.4") # str ~ string

type(True)

print(type(None))
type(1)

a = 3 + 4
print(a)

b = 5
a + b

a= 6
a + b

x = 6
x= 5.2
print(x)

x = " I am"
y = "Legend!"
print(x)
print(y)

print(x,y)

x = 10
X = 20
print(X,x)

5_pulkit = 2

pulkit_5 = 2

pulkit5 = 4

_pulkit = 10

_ = 10 # highly recommend not to use this

x = 10
y = x
print(y)

x = 5
print(x)
print(y)

name = input()
print("Hello",name)

x = 3
y = 'hello'
num = y
y = 5
print(num, y)

"""Input function with numeric data"""

x = input()
y = input()
x + y # example of python's flexibility

print(type(x))
print(type(y))

"""type casting"""

x = input()
y = input()
int(x) + int(y) # example of python's flexibility

x = float(input())
y = float(input())
x + y

x = "this is a string"
int(x)

x = "10.5"
int(x)

x = 10
print(str(10))

type(None)

int(x) = input() # doubt from the class

