# -*- coding: utf-8 -*-
"""python_if_else_18Oct.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G1HppibYQE22R1ZWazcmT2ctnnOempvk
"""

if 56 > 50:
  print("1")
  print("2")

if 56 > 50:
  print("1")
  print("2")
print("3")

if 56 > 50:
  print("1")
print("3")

if True:
  #Run these statements
else:
  #Run these statements
#Run these always

a = 1
result = a**5
if result > 25:
  print("this is a big number")
else:
  print("this is not a big number")
print("code completed")

original_pass = "amazingstudents"
password = input("Enter your password")
if original_pass == password:
  print("correct password")
else:
  print("incorrect password")

"""#
# input: hour of the day

1. 9 to 12 : good morning
2. 12 to 17: good afternoon
3. 5 to 24: good night
4. else: please sleep
"""

time = int(input())
if 9<=time<12:
  print("Good morning")
else:
  if time >= 12 and time < 17:
    print("Good afternoon")
  else:
    if time >= 17 and time < 24:
      print("Good night")
    else:
      print("please sleep")
print("execution finished")

#ATM cash problem. only 200 and 500 is possible
amount = int(input("Enter the amount"))
if amount%200 == 0 or amount%500 == 0:
  print("please collect your cash")
else:
  print("requested cash cannot be dispensed")

# quiz explanation
x = 0
if x:
    print("True")
else:
    print("False")

bool(0)

# elif block

if condition1:
  this
elif condition2:
  this
else:
  this

time = int(input())
if 9<=time<12:
  print("Good morning")
  print("how are you?")
elif time >= 12 and time < 17:
  print("Good afternoon")
  print("how are you?")
elif time >= 17 and time < 24:
  print("Good night")
  print("how are you?")
elif time >= 24:
  print("please don't give incorrect values")
else:
  print("please sleep")
  print("how are you?")
print("execution finished")

amount = int(input('Enter amount: '))
if amount <= 500 and (amount%500)%200 == 0:
  print('Discharging cash')
elif amount > 500 and ((amount%500)%200)%100 == 0:
  print('Discharging cash')
else:
  print('Denomination not available')

# odd-even code
x = int(input())
if x%2 == 0:
  print("even")
else:
  print("odd")

# anjali's code ( doesn't work )
a=int(input("enter amount"))
if a%500==0 or (a%500)%200==0 or (a%200)%500==0 or a%200==0:
  print("please collect cash")
else:
  print("cash not available")

#quiz 3
x = 5
if x > 2:
    if x < 10:
        print("x is between 2 and 10")
    else:
        print("x is greater than or equal to 10")
else:
    print("x is less than or equal to 2")