# -*- coding: utf-8 -*-
"""lambda_lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idRQUn0uaheJAnffbKh6hV0okyl4eLM7
"""

def add_10(x):
  return x + 10
add_10(5)

add_15 = lambda x: x + 15

add_15(10)

def string_combine(x,y):
  return x + ","+y

string_combine("Pulkit","Aneja")

str_comb2 = lambda a,b: a + "," + b
str_comb2("Best","Batch")

# using lambda without storing it (anonymous functions)
(lambda a,b: a + "," + b)("Best","Batch")

"""List"""

runs_virat = [67,54,12,34,77,89,102] # arrays

print(runs_virat)

runs_virat[0]

runs_virat[1]

runs_virat[6]

len(runs_virat)

runs_virat[len(runs_virat)-1] # C++/Java

# negative indexes (pythonic)
runs_virat[-1]

runs_virat[-4]

runs_virat[3]

# append (add an element at the end of the list)
runs_virat.append(120)

runs_virat

len(runs_virat)

# insert
runs_virat.insert(0,25)

runs_virat

# extend
runs_virat.extend([45,35,85])

runs_virat

# using + sign to add values to a list
runs_virat + [100,99]

runs_virat # the value of list did not get updated after addition operation

runs_virat = runs_virat + [100,99]

runs_virat

runs_virat.pop(2) #returning the removed value and also updating the list

runs_virat

runs_virat.pop()

runs_virat.append(120)

runs_virat

runs_virat.remove(120) # removes the first occurance of any value

runs_virat

runs_virat.remove(34)
runs_virat

runs_virat.count(100)

my_list = [1,2,3,4,5]

3 in my_list #

6 not in my_list

my_list = [10,22,11,34,56]
my_list.index(11) # how will this function behave if there are multiple occurences?

salaries = [10000, 210000, 320000, 9000, 90000]

for i in salaries:
  print(i)

my_list = [1, 2, 3, 4, 5]
i = -1
while i >= -5:
    print(my_list[i], end=" ")
    i -= 1

"""#Solving question"""

runs_virat = [67, 54, 12, 34, 77, 89, 101]

# find sum, average, min and max

sum_runs = 0
for i in runs_virat:
  sum_runs+=i
print(sum_runs)

# find length of the given list
len_runs = 0
for i in runs_virat:
  len_runs+=1
print(len_runs)

sum_runs/len_runs

# find the max value in the list
max_val = 0
for i in runs_virat:
  if max_val < i:
    max_val = i

print(max_val)

#h.w: please try min

sum(runs_virat)

len(runs_virat)

mean(runs_virat) # mean function does not exist

min(runs_virat)

max(runs_virat)

my_list = ["apple", "banana", "orange"]
for i in range(len(my_list)):
    print(my_list[i] + " is a fruit.", end=" ")

#Calculate the sum of runs made by Virat Kohli in all matches with even index.

sum_runs = 0
for i in range(len(runs_virat)):
  if i%2 == 0:
    sum_runs += runs_virat[i]

sum_runs

len(2543)