# -*- coding: utf-8 -*-
"""sets_tuples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1awvsCH-gSB8z6Ada0vWU8IXnt15GHPUo

Mutability: whose value can be changed
"""

a = 3
a = 4
print(a)

id(a)

a = 6
id(a)

"""mutable data types: lists, dictionaries, sets"""

my_list =["Python", "C++", "Java"]
id(my_list)

my_list[0] = "Python3"
my_list

id(my_list)

name = "Pulkit"
name[3]

name[3] = 'p' #strings are immutable

name = "Rachit"
id(name)

name.replace("R","K")

"""# Tuples"""

a = (1,2,3,4,5)
a

print(type(a))

a[3]

a[3] = 5 # tuples are immutable

planets = ["Mercury","Venus","Earth"]
planets[0] = "Planet Pulkit"
planets

planets_new = tuple(planets)
planets_new

planets_new.append("Mars")

planets_new[-1]

planets_new[:1]

planets[:1]

t = (23,32)
type(t)

planets.pop()

t = (23)
type(t)

t

t = (23,)
type(t)

t

# unpacking

a = (1,2,3)

x,y,z = a

print(x)
print(y)
print(z)

def foo():
  return 200,300,400

bar = foo()
print(bar)

a,b,c = foo()

a,b = foo()

a = [(1, "Bipin"), (2, "Ranjan"), (3, "Shanoor"), (4, "Shital"), (5, "Tharoor")]

a[3] = (7,"James Bond")

a[3][0] = 8

x = (1, 2, 3)
y = (4, 5, 6)
z = x + y
print(len(z))

z

a = ()
type(a)

a = tuple()
a

"""Swapping"""

a = 10
b = 30

# additional memory method
temp = a
a = b
b = temp

print(a,b)

# without additional memory 40
a = 10
b = 30

a = a + b
b = a - b # a + b - b
a = a - b

print(a,b)

a = b
b = a

a = 10
b = 30
a,b = b,a

print(a,b)

"""# Sets"""

s = {1,2,3,4}
print(s)

type(s)

s = {1,2,3,4,1,2,4}
print(s)

s[0] # sets are unordered

s = {}
print(s)

type(s)

s = set()
s

type(s)

s = {True, "Pulkit", 7, 'Pulkit'}
s

s = {True, "Pulkit", 7, 'Pulkit', ["Pulkit","Aneja"]} # why lists cannot be added to a set

s = {True, "Pulkit", 7, 'Pulkit', ("Pulkit","Aneja")}

"""# Set methods"""

s = {1,2,3}

s.add(4)
s

s.remove(3)
s

s.pop()

s

s = {True, "Pulkit", 7, 'Pulkit', ("Pulkit","Aneja")}
s

s.pop()

# pop method in set removes the first element that was added

s = {2,4}
s.update([1,2,3,4,5])
s

s.update(1,2,3)

s.update((5,6,7)) # set, tuples, list anything is ok as all of them are iterable

s

type(t)

for i in t:
  print(i)

for i in s:
  print(i)

ls = [1,2,3,1,5,1]
s = set(ls)
s

a,b = [1,2]
print(a,b)

a,b = {1,2}
print(a,b)

