# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFiyTV_iBdDqUI9_lq-m0EgpPg7EWrf9

**Q1. Divide the tuple**

**Problem Description:**

Write a program to divide a given tuple into two tuples that contain even and odd indexed elements of the original tuple. Print both these tuples in the given output format.

**Note:** The input tuple follows 1-based indexing. This means the element at index 0 is treated as having index as 1.

For example, (9,2,3). The 1-based index of 2 is 2.
"""

def odd_even_split_tuple(tup):
    ''' input:tup-indicates the tuple
         output:print two tuples one for even indexed and odd indexed in the given output format'''

    # YOUR CODE GOES HERE
    return tup[::2], tup[1::2]

tup = (10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
odd_tup, even_tup = odd_even_split_tuple(tup)
print(f"odd_even_split_tuple({tup}) =>\n\tOdd = {odd_tup}\n\tEven = {even_tup}")

"""**Q2. Adding to a tuple**

Predict the output of the following code as we are trying to append to an immutable tuple:

```python
name_lst = ["Vijay", "Vickey"]
tup = ("Item_1", 0.5, name_lst)
name_lst.append("Vishal")
print(tup)
```
"""

name_lst = ["Vijay", "Vickey"]
tup = ("Item_1", 0.5, name_lst)
name_lst.append("Vishal")
print(tup)

"""**Q3. Tuples Trap**

Find output of the following:

```python
tuple1 = (1150, 'sea_level', 901)
print(max(tuple1))
tuple1 = (1150, 877, 909)
print(max(tuple1))
tuple1[0] = 50
print(tuple1[0])
```
"""

tuple1 = (1150, 'sea_level', 901)
print(max(tuple1))
tuple1 = (1150, 877, 909)
print(max(tuple1))
tuple1[0] = 50
print(tuple1[0])

"""**Q4. Length of unique words**

**Problem Description:**

Given two sentences, write a program to return the sum of the total number of unique words from each sentence.
"""

def set_operation(sent1,sent2):
    ''' input:sent1,sent2-two sentences taken as inputs
         output:return the sum of length of unique words.'''

    # YOUR CODE GOES HERE
    unique_words = set(sent1.split(" "))
    unique_words.update(set(sent2.split(" ")))
    return len(unique_words)

sent1 = '''
The first line indicates the number of test cases.There will be two lines of inputs for each test cases as following:
'''

sent2 = '''
The two lines consist of two sentences in string format.
'''
print(f"set_operation('{sent1}','{sent2}') = {set_operation(sent1,sent2)}")

"""**Q5. Length of Sets**

What is the output of the following program?

```python
set1 = {1, 2, 4}
set2 = {4, 5, 6}
print(len(set1 + set2))
```
"""

set1 = {1, 2, 4}
set2 = {4, 5, 6}
print(len(set1 + set2))

"""**AQ1. Making Sets**

Which of the options defines a set s consisting of strings 'Scaler', 'Academy', 'is', and 'Awesome'?

```python
s = set(['Scaler', 'Academy', 'is', 'Awesome'])
s = set('Scaler', 'Academy', 'is', 'Awesome')
s = set('Scaler Academy is Awesome')
s ={'Scaler', 'Academy', 'is', 'Awesome'}
```
"""

s = set(['Scaler', 'Academy', 'is', 'Awesome'])
print(f"{s} is of type {type(s)}")
# The below results in syntax error!
# s = set('Scaler', 'Academy', 'is', 'Awesome')
s = set('Scaler Academy is Awesome')
print(f"{s} is of type {type(s)}")
s ={'Scaler', 'Academy', 'is', 'Awesome'}
print(f"{s} is of type {type(s)}")

"""**AQ2. Updating Elements**

Complete the code snippet with possible statements from options so that the expected output is obtained.

```python
sets = {3, 4, 5}
???
print(sets)
```

**Expected Output:** {1, 2, 3, 4, 5}

```python
sets.update([1, 2, 3])
sets.add([1, 2 ,3])
sets += [1, 2 ,3]
sets += {1, 2, 3}
sets = sets.union({1, 2, 3})
```
"""

sets = {3, 4, 5}
sets.update([1, 2, 3])
print(sets)

# TypeError: unhashable type: 'list'
# sets = {3, 4, 5}
# sets.add([1, 2 ,3])
# print(sets)

# TypeError: unsupported operand type(s) for +=: 'set' and 'list'
# sets = {3, 4, 5}
# sets += [1, 2 ,3]
# print(sets)

# TypeError: unsupported operand type(s) for +=: 'set' and 'set'
# sets = {3, 4, 5}
# sets += {1, 2, 3}
# print(sets)

sets = {3, 4, 5}
sets = sets.union({1, 2, 3})
print(sets)

"""**AQ3. Indexing Sets**

Given the names of students in the following set. There was a grammatical mistake in the name "Aurn". It should be 'Arun'. What will be the output if we try to execute the code given below in order to update this name?

```python
a={'Aurn', 'Nikhil', 'Seeta'}
a[0]= 'Arun'
print(a)
```
"""

a={'Aurn', 'Nikhil', 'Seeta'}
# TypeError: 'set' object does not support item assignment
#a[0]= 'Arun'
print(a)

"""**AQ4. Frequency of unique elements**

**Problem Description:**

Write a function to print out the frequency of all the unique elements present in a given tuple.

**Input Format:**

> The one input line consists of a tuple.

**Output Format:**

```
Unique elements and their frequencies are expected to be printed
as follows:  
unique_element1 : freq1  
unique_element2 : freq2  
.  
.
```

**Sample Input 1:**
(10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)

**Sample Output 1:**

10 : 3

8 : 4

5 : 2

2 : 2

15 : 1  

**Sample Input 2:**

(100, -10, -10, “ONE”, [22], [22], “ONE”)

**Sample Output 2:**

100 : 1

-10 : 2

ONE : 2

[22] : 2
"""

def unique_count(tup):
    ''' input:tup-indicates the tuple
         output:Print the unique elements and their frequency'''
    elements_count = {}
    for e in tup:
        key = str(e) # Convert to string so that it is easily hashable and also easy to print
        if key in elements_count:
            elements_count[key] += 1
        else:
            elements_count[key] = 1

    for key, count in elements_count.items():
        print(f"{key} : {count}")

tup = (10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
unique_count(tup)
tup = (100, -10, -10, "ONE", [22], [22], "ONE")
unique_count(tup)

"""**AQ5. Access Tuples**

What is the output of the following:

```python
elements = (10, 20, 30, 40, 50, 60, 70, 80)
print(elements[2:5], elements[:4], elements[3:100])
```
"""

elements = (10, 20, 30, 40, 50, 60, 70, 80)
print(elements[2:5], elements[:4], elements[3:100])

"""**AQ6. Symmetric difference**

**Problem Description**

Write a program that returns the symmetric difference of two sets, without actually using the symmetric difference operator.
"""

def symm_diff(set1, set2 ):
    ''' input:set1,set2-two sets
        output:return symmetric difference set
    '''

    # YOUR CODE GOES HERE
    return set1.difference(set2).union(set2.difference(set1))

set1 = {10, 20, 30, 40}
set2 = {30, 40, 50, 60}
print(f"symm_diff({set1}, {set2}) = {symm_diff(set1, set2)}")