# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9YR2xL3cGauDssWmcJ1XNPiJG0MplfT

$\newcommand{\trinom}[3]{\begin{pmatrix} #1 \\ #2 \\ #3 \end{pmatrix}}$

# **Q1. Maxpower or year ?**

Given the linear regression price prediction equation,


price = w1 * maxpower + w2 * year + w3 * engine +.....+ w0


where w1=2 and w2 = 0.5.


Out of w1 and w2, which feature is/are more important in determining the target variable?

#### **Ans:**

TBD. Need to discuss on the feature scaling aspect here once, eventhough Scaler says w1 is more important!

# **Q2. Calculate adjusted R-squared**

Given the train and test data, fit a linear regression model on the train data and calculate the adjusted R-squared rounded up to 2 decimal places on the test data for this model.
"""

import numpy as np

#import linear regression model
from sklearn.linear_model import LinearRegression

def adj_rsq(xtrain, ytrain, xtest, ytest):

   xtrain = np.asarray(xtrain)
   ytrain = np.asarray(ytrain)
   xtest = np.asarray(xtest)
   ytest = np.asarray(ytest)

   #initialize the linear regression model
   reg = LinearRegression()

   #Train the model on train data
   reg.fit(xtrain, ytrain)

   #get the R-squared for the model for xtest and ytest
   r2_sq = reg.score(xtest, ytest)

   #calculate the adjusted R-squared using R-squared.
   adjr2_sq = 1 - ((1 - r2_sq) * (ytest.size - 1) / (ytest.size - xtest.shape[1] - 1))
   return np.round(adjr2_sq, 2)

xtrain = [[6, 9, 3], [4, 4, 8], [14, 3, 0], [5, 4, 12], [13, 10, 12], [2, 10, 2], [10, 3, 1], [13, 8, 7], [14, 0, 7], [11, 5, 3], [13, 14, 10], [12, 1, 3], [0, 9, 6], [12, 9, 11], [11, 8, 11], [2, 13, 3], [7, 0, 8], [14, 13, 5], [10, 5, 11], [4, 3, 13]]
ytrain = [10, 13, 28, 37, 27, 12, 24, 4, 7, 9, 8, 2, 1, 38, 35, 12, 8, 26, 10, 7]
xtest = [[9, 7, 8], [0, 5, 9], [8, 5, 9], [14, 5, 0], [8, 0, 1], [3, 6, 11], [2, 2, 11], [1, 7, 3], [8, 3, 14], [11, 14, 10]]
ytest = [16, 3, 18, 30, 16, 10, 22, 9, 6, 6]

print(f"Adjusted R-squared = {adj_rsq(xtrain, ytrain, xtest, ytest)}")

"""# **Q3. Maxima and Minima of R-squared**

What will be the minima and maxima for the R-squared metric? The formula for R-squared is shown below:

$R^2 = 1 - RSS/TSS$

Where **RSS** is the Sum of Squared Residuals and **TSS** is the Total sum of Squares

#### **Ans:**

Minima = $-\infty$, Maxima = 1

# **Q4. Infinity and beyond**

When will the value of R-square tend to -infinity (-$\infty$)?

#### **Ans:**

When RSS >> TSS and RSS tends to infinity ($\infty$)
"""