# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9YR2xL3cGauDssWmcJ1XNPiJG0MplfT

$\newcommand{\trinom}[3]{\begin{pmatrix} #1 \\ #2 \\ #3 \end{pmatrix}}$

# **Q1. Higher Lambda**

Say you are using regularization with higher lambda while solving a linear regression problem but you found out that the training error of your model is 60% and the testing error is 65%, what can be the possible solution to this problem?

#### **Ans:**

Decrease lambda in regularization.

**Explanation:**

This situation represents the situation of underfitting where weights are too much penalized that ***hypothesis is getting more linear***. (The higher degree variables combined with reduced weights are not influencing the hypothesis)

Decreasing the lambda will make decreasing the penalizing effect of regularization to some extent and hypothesis can fit the data properly.

# **Q2. Useless features**

Mark the correct options which are true regarding the optimization equation of regularization?

**Options:**

1. Square sum of weights is trying to make all the weights closer to zero.
2. Square sum of weights is trying to make all the weights non-zero.
3. Square sum of residuals is trying to make all the weights of significant features closer to zero.
4. Square sum of residuals is trying to make all the weights of significant features non-zero.

#### **Ans:**

Options 1 & 4:
* Square sum of weights is trying to make all the weights closer to zero.
* Square sum of residuals is trying to make all the weights of significant features non-zero.

**Explanation:**
* Optimizing/minimizing on the regularization term $\lambda\Sigma_1^kw_i$ is trying to make all weights closer to zero as it is not checking on any criteria unlike loss term.
* Optimizing/minimizing on the MSE $1/n\Sigma_1^m(y_i - \hat{y_i})^2$ is trying to select best weights possible for the features according to the difference of actual and predicted value.

# **Q3. Update weights.**

Given the 1d input features X and target Y. Use Gradient descent to get the optimal weights for the Linear regression model that uses Mean Squared Error(MSE) with L2 regularization.

* The hypothesis function for Linear regression is $\hat{Y} = wX + b$.

* The cost function = $L(w)= 1/2m(\Sigma_{i=1}^m(\hat{Y}_i - Y_i)^2 + \lambda\Sigma_{j=1}^{d}w_j^2)$

Use the below functions to compute the gradient for a single weight w and bias b :

1. w's gradient = $1/m(\Sigma_{i=1}^m(\hat{Y}_i - Y_i)X_i + \lambda w_j)$

2. b's gradient = $1/m(\Sigma_{i=1}^m(\hat{Y}_i - Y_i))$

m is the number of samples,

d is the number of features,

$\lambda$ here is the regularization parameter.

Complete the function to perform L2 regularization and return new updated weight w and bias b, rounded up to 2-decimal places.
"""

import numpy as np

def L2_reg_update_weights(w, b, X, Y, learning_rate, lambda_value=1):
    """input: w is the coefficient of x in form of an integer.
              b is the constant term, integer format.
              X is a python list of input variables.
              Y is a python list of the output variables.
              learning_rate is in the form of float.
              lambda_value is an integer which is actually the penalty term in l2 regularization.
        output: You are required to return updated m and b upto two decimal points, in the same line.
    """

    X = np.asarray(X)
    Y = np.asarray(Y)

    Y_hat = w * X + b
    n = len(Y)

    w_deriv = np.sum(np.dot(Y_hat-Y,X) + lambda_value*w)/n
    b_deriv = np.sum(Y_hat - Y)/n


    # Update weights
    w -= learning_rate * w_deriv
    b -= learning_rate * b_deriv

    return(round(w, 2), round(b, 2))

"""# **Q4. Bias and Variance in Ridge Regression**

The cost/loss function of Ridge Regression is:

$L(w) = MSE(W) + \lambda\Sigma_{j=1}^d w_j^2$

Here, hyperparameter $'\lambda'$ denotes the amount of regularization How do the values of $'\lambda'$ affect the line of best fit?

**Statements:**

1. Both, Bias & Variance are low in case of very large lambda.
2. Bias is low & Variance is high in case of very small lambda.
3. Bias is high & Variance is low in case of very large lambda.
4. Both, Bias & Variance are high in case of very small lambda.

#### **Ans:**

Statements 2 & 3:

* Bias is low & Variance is high in case of very small lambda.
* Bias is high & Variance is low in case of very large lambda.

# **Q5. Lasso Regression**

**Problem Description:**

Given the training data, train a Lasso regression model and print out the coefficients and intercept.
"""

import numpy as np


#import Lasso Regression class from scikit-learn library
from sklearn.linear_model import Lasso

def coefficientsAndIntercept(xTrain, yTrain):
    # convert lists into numpy array
    X_train = np.asarray(xTrain)
    y_train = np.asarray(yTrain)

    # initialize Lasso regression and set the value of alpha equal to 1
    regressor = Lasso(alpha = 1)

    # fit the model
    regressor.fit(X_train, y_train)

    #print intercepts and coefficients rounded off upto 2 decimal digits
    print(np.round(regressor.coef_, 2))
    print(np.round(regressor.intercept_, 2))

"""# **Q6. Regularization**

In linear regression, which loss function is most suitable for regularization and variable selection?

1. $LOSS = 1/N\Sigma_{i=1}^{N}MSE(y_i, \hat{y_i}) + \lambda/N\Sigma_{j=1}^{d}|w_j|$
2. $LOSS =1/N\Sigma_{i=1}^{N}MSE(y_i, \hat{y_i}) + \lambda/N\Sigma_{j=1}^{d}w_j^2$

**Options:**

1. 1, because it will move weight of less useful features towards zero in fewer steps.
2. 2, because it will move any weight towards zero in fewer steps.
3. Both 1 and 2, because they will move any weight towards zero in equal steps.
4. None of 1 and 2, because we don't need to do variable selection

#### **Ans:**

Option 1: 1, because it will move weight of less useful features towards zero in fewer steps.

# **AQ1. Regularization Necessity**

If we don't run a correlation check before applying regularization, it will always cause a very wrong result in predictions. Is the above statement true? What's the reason for it being true or false?

**Options:**

1. False, because if we don't run a correlation check, regularization will make all the weights equal to zero irrespective of their significance in prediction.
2. True, because if we don't run a correlation check, regularization won't be able to handle correlated features.
3. False, because even if we don't run a correlation check regularization can handle correlated features.
4. True, because even if we don't run a correlation check regularization will treat all the features equally and will give the weights as equally significant.

#### **Ans:**

Option 3: False, because even if we don't run a correlation check regularization can handle correlated features.

**Explanation:**

* Using regularization, the weights of useless features will become close to zero and this way correlation can also be handled because
    * If there are two correlated features then only one of them will end up with a significant weight.
* The algorithm is penalizing all the correlated variables and taking only one among them.

# **AQ2. Which Regularization?**

Which regularization is used to reduce the over fit problem?

### **Ans:**

Both L1 & L2.

**Explanation:**

* Both L1 and L2 regularization methods are used to reduce the overfit problem
* L1 regularization, also known as L1 norm or Lasso (in regression problems), combats overfitting by shrinking the parameters towards 0. This makes some features obsolete.
* L2 regularization, or the L2 norm, or Ridge (in regression problems), combats overfitting by forcing weights to be small, but not making them exactly 0.

# **AQ3. ElasticNet Regularisation**

Given the training and test data, return the predictions for the test data using Elastic net regularized linear regression, rounded up to two decimal places.
"""

import numpy as np

#import elastic net regularized linear regression model
from sklearn.linear_model import ElasticNet


def prediction(xtrain, ytrain, xtest):

    #intantiate the model
    elnet = ElasticNet()

    #train the model
    elnet.fit(xtrain, ytrain)

    #Calculate the prediction for test data
    prd = elnet.predict(xtest)

    return np.round(prd, 2)