# -*- coding: utf-8 -*-
"""1-Notes- Intro to ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovsNaFr0hTAZ7AR8mPNswoqH0R6Yv035

## Content
- Agenda
- Already Learnt
- DSML Libraries
  - Plotting Examples
  - Prob and Stats
  - Linear Algebra
- TO Learn
- ML v/s Classical Programming
  - SDE vs ML Pipeline
  - Tom Mitchell's definition of ML Task
  - ETP
- ML: Categorisation based on Tasks

  - Classifcation
  - Regression      
  - Classification v/s Regression
  - Supervised Learning
  - Clustering
  - Unsupervised Learning

### Agenda

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/040/558/original/image_2023-07-24_182421442.png?1690203260" width=800>

### ALREADY LEARNT

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/040/559/original/image_2023-07-24_182504594.png?1690203303" width=800>

### DSML Libraries

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/040/560/original/image_2023-07-24_182558308.png?1690203357" width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/040/561/original/image_2023-07-24_182626953.png?1690203386" width=800>

#### Plotting Examples

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/040/562/original/image_2023-07-24_182701379.png?1690203420" width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/040/563/original/image_2023-07-24_182726689.png?1690203445" width=800>

#### Probability and Statistics

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/040/564/original/image_2023-07-24_182821507.png?1690203501" width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/040/565/original/image_2023-07-24_182842139.png?1690203522" width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/040/566/original/image_2023-07-24_182903357.png?1690203542" width=800>

#### Linear Algebra

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/040/568/original/image_2023-07-24_182949719.png?1690203588" width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/040/569/original/image_2023-07-24_183018451.png?1690203616" width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/040/570/original/image_2023-07-24_183036998.png?1690203636" width=800>

### TO LEARN

### ML v/s Classical Programming

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/493/original/image.png?1705055311" width=800>

#### **How does the SDE pipleline look?**

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/494/original/image.png?1705055395" width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/495/original/image.png?1705055456" width=800>

#### How does the ML pipeline look?

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/496/original/image.png?1705055673" width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/497/original/image.png?1705055757" width=800>

#### "Well defined" ML task - Definition by Tom Mitchell

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/498/original/image.png?1705055955" width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/499/original/image.png?1705056084" width=800>

#### ETP Example

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/502/original/image.png?1705056196" width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/504/original/image.png?1705056357" width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/505/original/image.png?1705056480" width=800>

#### ML Topics Categorisation

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/510/original/img.png?1705056694' width=800>

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/511/original/img.png?1705056821' width=800>

### ML Categorisation based on Tasks

#### Classification

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/513/original/img.png?1705057029' width=800>

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/514/original/img.png?1705057062' width=800>

#### Regression

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/516/original/z.png?1705057163' width=800>

#### Regression v/s Classification

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/519/original/z.png?1705057208' width=800>

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/523/original/z.png?1705057297' width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/504/original/image.png?1705056357" width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/505/original/image.png?1705056480" width=800>

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/524/original/z.png?1705057450' width=800>

#### Supervised Learning

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/525/original/z.png?1705057493' width=800>

#### Clustering

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/528/original/z.png?1705057589' width=800>

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/529/original/z.png?1705057636' width=800>

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/530/original/z.png?1705057671' width=800>

#### Unsupervised Learning

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/531/original/z.png?1705057724' width=800>

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/532/original/z.png?1705057905' width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/504/original/image.png?1705056357" width=800>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/505/original/image.png?1705056480" width=800>

<img src='https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/061/534/original/z.png?1705057956' width=800>
"""

