# -*- coding: utf-8 -*-
"""Usecase EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nkbiGCMrevDzdSG9yN5bXaxeC8CPJSQg

Lets Load the data
"""

#Churn prediction in telecom.
import numpy as np
import matplotlib.pyplot as plt

!gdown 1uUt7uL-VuF_5cpodYRiriEwhsldeEp3m

import pandas as pd
churn = pd.read_csv("churn_logistic.csv")
churn.head()

"""**Data Description**
<center>

| Records | Features |
| :-- | :-- |
| 5700 | 21 |


| Id | Features | Description |
| :-- | :--| :--|
|01| **state** | 2-letter code of the US state of customer residence|
|02| **account_length** | Number of months the customer has been with the current telco provider |
|03|**area_code**|string="area_code_AAA" where AAA = 3 digit area code|
|04|**intl_plan**|The customer has international plan|
|05|**vmail_plan**| The customer has voice mail plan|
|06|**vmail_messages**|Number of voice-mail messages|
|07|**day_mins**|Total minutes of day calls|
|08|**day_calls**|Total no of day calls|
|09|**day_charge**|Total charge of day calls|
|10|**eve_mins**|Total minutes of evening calls|
|11|**eve_calls**|Total no of evening calls|
|12|**eve_charge**|Total charge of evening calls|
|13|**night_mins**|Total minutes of night calls|
|14|**night_calls**|Total no of night calls|
|15|**night_charge**|Total charge of night calls|
|16|**intl_mins**|Total minutes of international calls|
|17|**intl_calls**|Total no of international calls|
|18|**intl_charge**|Total charge of international calls|
|19|**customer_service_calls**|Number of calls to customer service|
|20|**phone**|10 digit number|
|21|**churn**|Customer churn - target variable|

Lets see the number of samples when $y=0$ and $y=1$
"""

churn["Churn"].value_counts()

"""**Observe**

The samples for both the values of $y$ are same
- Showing that the data is balanced or have equal number of samples for both the cases

Now lets see how each feature is effective in predicting Churn or Not by performing a univariate EDA
"""

import seaborn as sns
sns.boxplot(x='Churn', y='Day Mins', data = churn)

"""- Notice how we use feature ```Day Mins``` to check if it is significant or not

#### What can we see from the boxplot ?
- The churned custmors have a higher median for  Day Mins than not churned customers which means:
- Customer who spent more time calling in a day tend to churn

this shows, ```Days Mins``` is an important feature

Now, let's see if there is any other feature which has collinearity with ```Days Mins```
"""

sns.pairplot(data=churn, y_vars=["Day Mins"], x_vars=['Account Length', 'VMail Message' , 'Eve Mins', 'Night Mins',
       'Intl Mins', 'CustServ Calls', 'Churn', 'Intl Plan', 'VMail Plan',
       'Day Calls', 'Day Charge', 'Eve Calls', 'Eve Charge', 'Night Calls',
       'Night Charge', 'Intl Calls', 'Intl Charge'], height=1.5, aspect=1)
plt.show()

"""#### Can we say which feature is highly correlated with ```Days Mins``` ?
- Day Charge is highly correlated
- Hence we will just drop either one of them

Now lets see another feature ``` Account Length```
"""

sns.boxplot(x = 'Churn', y= 'Account Length', data = churn)

"""#### Does the Account Length feature relevant ?
- If we see median for both, its quite similar
- Hence this feature does not have any signficance and can be dropped

Let's plot few more boxplots and check for outliers too
"""

sns.boxplot(x = 'Churn', y= 'Eve Mins', data = churn)

sns.boxplot(x = 'Churn', y= 'Intl Plan', data = churn)

"""Notice how this feature is completely inclined towards one, hence we will not be taking this feature"""

sns.boxplot(x = 'Churn', y= 'CustServ Calls', data = churn)

sns.boxplot(x='Churn', y='VMail Message', data=churn)

"""Again, notice here how there are a lot of outliers for label 1. Hence we will not be taking this feature"""

sns.boxplot(x='Churn', y='Night Mins', data=churn)

sns.pairplot(data=churn)

"""Notice how,

- Day Charge and Day Mins are correlated completely
- Similar for Night Charge and Night Mins, and Eve Charge and Eve Mins
- We will be taking one of these features each
- We will also be taking few more features such as "Account Length" and "CustServ Calls"

This was a very basic level EDA to choose which features to choose for our LogisticRegression model. You can do your own analysis and try to apply more techniques of feature selection
"""